### ISSUE TITLE
Crash: [AWSTaskCompletionSource setResult:] (AWSTaskCompletionSource.m:46)

### ISSUE THREAD

**Issue by savage7** [aws-amplify/aws-sdk-ios#1024]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.6.11, updated to 2.6.27. Problem still exists

* Is the issue limited to Simulators / Actual Devices?
Actual Devices. Very hard to reproduce.

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
Probably not, using the latest iOS Version 11.4.1

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
The thing is that it works for 99%. We do a login like described here:
https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-ios-sdk.html

It works but sometimes, for some users it crashes. It looks similar to this: https://github.com/aws/aws-sdk-ios/issues/913

Crash log:
[crash.txt](https://github.com/aws/aws-sdk-ios/files/2302591/crash.txt)

We save the AWSTaskCompletionSource like this:
@property (nonatomic, strong) AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails*>* passwordAuthenticationCompletion;

When the user enters the username&password we do:
passwordAuthenticationCompletion.result = result;

This leads to a crash sometimes. Which is in fact very hard to reproduce but it happens and the device doesn't recover from it. Even deleting the app doesn't help. I added some code to completely delete the keychain, but this didn't help either.

**Comment by cbommas** [comment]
@savage7 

This looks like a timing issue. The crash is happening because of a safegaurd on AWSTaskCompletionSource that prevents a result being set on it after the Task has been flagged as completed.

Can you share a code snippet to help debug this further?

**Comment by mehulmistri** [comment]
Version 2.7.3 has the same issue, when we  set `passwordAuthenticationCompletion.result`. Please post if there are any findings.

**Comment by swickes** [comment]
Any solution to this? (Apple is rejecting one of my apps for this exact reason. AWSTaskCompletionSource line 46). I will appreciate any news!
Thanks

**Comment by swickes** [comment]
I think I found a SOLUTION - for my case anyway. I can consistently create the crash by quickly double-tapping my "Sign In" button. Now, I disable the button after the first touch and voila - no more NSException and crash from AWSTaskCompletionSource.m. (Of course I have to re-enable the Sign In button after "bad password alerts, etc.) Hope this helps someone!

**Comment by rohandubal** [comment]
Hello everyone,

Apologies for the delayed response on this thread. I was investigating this issue and reached a conclusion that this error happens when the `result` on `TaskCompletionSource` is set twice. 

In the example mentioned by @swickes the error was resolved since the disabled button ensures that the result is not set on the `TaskCompletionSource`. 

To ensure that this issue does not impact developers at all, would involve a big change in the SDK(moving away from TaskCompletionSource.) We have implemented a simplified API implementation for CognitoUserPools in [`AWSMobileClient`](https://aws-amplify.github.io/docs/ios/authentication). It does not use TaskCompletionSource and ensures that this error does not occur.

That being said, I understand it is difficult to migrate to another library. So I have a recommendation for these use-cases where the crash can be avoided within limits of existing API. Since the behavior is controlled by `AWSTask` about what to do when there are multiple calls to `result`, I can recommend using `trySet(result:..)` which would look something like this:

```
let _  = passwordAuthenticationCompletion.trySet(result: <Result_HERE>)
```

The behavior of `trySet(result:)` is that, if the result is already set once, it will ignore the next set for the same `TaskCompletionSource`.

Please try it out and let us know if this issue still exists.

Thanks,
Rohan
