### ISSUE TITLE
Handling duplicate header fields

### ISSUE THREAD

**Issue by eimantas** [aws-amplify/aws-sdk-ios#1098]
I am exploring [aws rest api](https://docs.aws.amazon.com/general/latest/gr/Welcome.html) (and particularly [how to sign requests](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html)) by using [its test suite](https://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html) to see if my code generates proper canonical request and string to sign as well as properly signs the request. 

I'm using Swift 4.2.  I was wondering how do you handle a test case where duplicate header names are provided? Using `set(_ value:forHTTPHeaderField:)` replaces the header if it has been set already, while `add(_ value:forHTTPHeaderField:)` appends it using a field value separator. Is it possible at all using Foundation framework?

**Comment by palpatim** [comment]
Hi @eimantas,

This repository is for the AWS Mobile SDK, which abstracts those requests into library calls and provides additional functionality for some services. Nonetheless, I'll see if I can answer your question.

I think you're asking about cases like `get-header-key-duplicate`, which includes the raw request payload:

```
GET / HTTP/1.1
Host:example.amazonaws.com
My-Header1:value2
My-Header1:value2
My-Header1:value1
X-Amz-Date:20150830T123600Z
```

As you allude to, Foundation models its HTTP header fields as a dictionary of `[String : String]`, so the add/set methods won't give you the behavior required by the test. (By extension, anything that deserializes data into an NSURLRequest would be forced to deserialize into a dictionary regardless of the source data structure. You'd have to use some entirely custom networking framework, as far as I can see.)

I can't speak for Apple, but my assumption is that they modeled it this way because the HTTP Header spec requires multiple headers of the same name to be modeled as a single header field with a list of (order dependent) values. Thus, the example above would be required to be interpretable as `My-Header1:value2,value2,value1`. 

The test case recognizes this in the canonical request, which does indeed represent that header as `my-header1:value2,value2,value1` (remembering that header field names are case-insensitive).

My conclusion is that no, you can't perform this exact test (where multiple `My-Header1` HTTP header are modeled as single header fields) using Foundation classes, although you can of course still test that the *equivalent* request is signed appropriately.

Hope this helps.

**Comment by eimantas** [comment]
Thanks @palpatim, this definitely has helped. So in conclusion - I should just generate uniquely named headers with order dependent values in canonical request, which goes into string to sign and then just sign it. As far as I _should_ be concerned, the Amazon AWS backends will recognize either of the options:

```
MyHeader-1: Value2
MyHeader-1: Value1
```

```
Myheader-1: Value2,Value1
```

Thanks again for your answer!
