### ISSUE TITLE
AWSMobileClient-Swift.h not found

### ISSUE THREAD

**Issue by baljakbratislav** [aws-amplify/aws-sdk-ios#1126]
I use Cocoapods to install your framework. Version for 'AWSMobileClient' is 2.7.3, and for 'AWSIoT' is 2.7.3. After installation, Xcode report me error with message ''AWSMobileClient/AWSMobileClient-Swift.h' file not found'. 
After that I downgrade both versions to 2.6.10, and now is working well.

Version of my Xcode is 10.1. 
Swift 4
MacOs Mojave 10.14.1

**Comment by palpatim** [comment]
The 2.7.0 version of AWSMobileClient is a mixed Swift and Objective-C project. I'm investigating to see if there is a project setting we missed, or whether we just need to update our integration docs (and changelog/release notes) to ensure that developers set header & framework search paths.

**Comment by rohandubal** [comment]
Hello @baljakbratislav 

Since the project was changed to be a Swift-ObjC code project from ObjC, you will have to do a clean build to clear all the cache files generated by XCode. You will also have to close your `xcworkspace` file and re-open it. You can clean the cache by pressing `CMD + Shift + K`

Hope this helps.

Thanks,
Rohan

**Comment by SergiusPaulus** [comment]
I am getting this also.  pod install reported that AWSMobileClient (2.9.1) was installed.  But Xcode is reporting: 'AWSMobileClient/AWSMobileClient-Swift.h' file not found

I did clean and also deleted derived data before building.  Attached file may be helpful.
![screen shot 2019-02-22 at 12 25 14 pm](https://user-images.githubusercontent.com/5297391/53262798-334d9a80-369d-11e9-90c2-3ba63c4520fa.png)

**Comment by Georycoco** [comment]
I am having the same problem with"AWSCognitoAuth_Internal.h"
Anyone have a solution?
![Uploading Screen Shot 2019-03-17 at 3.31.50 pm.png…]()

**Comment by SergiusPaulus** [comment]
I was able to resolve my issue by updating both my iOS project to deployment target 11.0 and this line in my Podfile

platform :ios, '11.0'

Before, both were set to 9.0.  I have no idea why this fixed things.

**Comment by jamesatfish** [comment]
Same issue here also using version 2.9.3 pods, both with project settings using iOS 9.0 and after trying the iOS 11.0 suggestion.

Rolling everything back to 2.9.1 resolved the issue.

**Comment by thomers** [comment]
@Georycoco Same here, "AWSCognitoAuth_Internal.h file not found."

**Comment by SergiusPaulus** [comment]
I forgot to mention, and this may be important, that my problem *only* occurred with Xcode's Simulator.  I had exact same problem with Microsoft's ADAL.  The <ADAL/ADAL.h> could not be found at times.  What fixed it for me is posted above.

**Comment by Foefirelord** [comment]
Getting this error now with 2.9.3 pods alongside `Could not build Objective-C module 'AWSMobileClient'` and `Cannot override a Self return type with a non-Self return type`.

None of the above proposed solutions have helped.

No amount of cleaning the build folder or updating the pods with the latest possible iOS target version have done anything to fix the issue.

**Comment by Gperez88** [comment]
same problem, when they solve it?

**Comment by FMJobr** [comment]
Same here.

**Comment by alionthego** [comment]
any solution for this yet.  Having same problem

**Comment by SergiusPaulus** [comment]
You already tried all the main answers in this Stack Overflow question?  https://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files

**Comment by thomers** [comment]
Have a look at https://github.com/aws-amplify/aws-sdk-ios/issues/1328

I could fix a similar issue by removing a few redundant pods from my Podfile.

**Comment by rohandubal** [comment]
As mentioned by @thomers, the issue regarding `AWSCognitoAuth_Internal` file not found is due to redundant dependencies. Please see #1328 for explanation. 

This looks to me more like a cocoapods bug which doen't correctly generate pods project. As @SergiusPaulus mentioned, setting the iOS platform resolves this issue.

**Comment by thomers** [comment]
Note: Setting the iOS platform did not resolve my issue, I had to (also) remove the redundant pod from my Podfile.

**Comment by FMJobr** [comment]
We're not using Cocoapods but Carthage

**Comment by rreimche** [comment]
I am having `Could not build Objective-C module 'AWSMobileClient'` and `Cannot override a Self return type with a non-Self return type` regardless of the target (I tried 9.0, 11.0, 12.1 und 12.2).

Libraries versions:

Using AWSAuthCore (2.9.4)
Using AWSAuthUI (2.9.4)
Using AWSCognitoIdentityProvider (2.9.4)
Using AWSCognitoIdentityProviderASF (1.0.1)
Using AWSCore (2.9.4)
Using AWSMobileClient (2.9.4)
Using AWSUserPoolsSignIn (2.9.4)

**Comment by rreimche** [comment]
There is an issue devote to the `Cannot override a Self return type with a non-Self return type`: https://github.com/aws-amplify/aws-sdk-ios/issues/1394

**Comment by jcridev** [comment]
The issue still persists. No amount of pod re-installing or pruning dependencies helps.

**Comment by rreimche** [comment]
Is there a way to bypass the bug? Maybe to use an earlier version of the software? Can I access an earlier version of the Tutorial then?

**Comment by Foefirelord** [comment]
Switching over to AWSMobileClient for authentication and removing all the older authentication-related code and pods (AWSCognitoAuth, AWSCognitoIdentityProvider, etc.) solved the problem.

The new AWSMobileClient has everything needed to setup authentication, whether using in-app views or the Hosted UI or a combination of in-app UI and direct-to-social login.

And the docs are now well-formatted and fairly thorough:
https://aws-amplify.github.io/docs/ios/authentication

**Comment by rohandubal** [comment]
Hello all,

Throughout the thread I am observing a bunch of issues causing the confusion around the type of error and scenario under which the error will happen. I will try to summarize the issues and fixes and identify the scenarios in which this still is an issue. 

Issue 1 (Resolved) - The error `Cannot override a Self return type with a non-Self return type` shows up in Xcode. This was due to incompatibility with Swift 5 and has been resolved with #1377 and is available in the latest SDKs

Issue 2 (Resolved)  -  The error `AWSCognitoAuth_Internal.h file not found.` appears when compiling. This issue happens if you are using both AWSMobileClient and AWSCognitoAuth in the same Podfile. Removing AWSCognitoAuth will resolve the issue. This is discussed in #1328 

Issue 3 (Needs details) - Some devs are reporting an issue where Xcode calls out that there is an error in compiling AWSMobileClient. The specific error is `AWSMobileClient-Swift.h not found `. I want to know what kind of configuration and tooling does this issue happen? Can someone post information about:
 - Xcode Version
 - Simulator Version
 - macOS Version

The best scenario would be if someone could provide a small project where we can reproduce this issue. I will try to reproduce this issue on my side in the meanswhile.

Thanks,
Rohan

**Comment by rajuashok** [comment]
FYI to fix the issue for me, I updated to latest xCode (Version 11.2.1 (11B500)) and ran 
`pod deintegrate`
`pod pod install --repo-update`

This got the build to work.

**Comment by AzharRaeisi** [comment]
Trick worked for me
