### ISSUE TITLE
-objc linker flag causes duplicate symbols

### ISSUE THREAD

**Issue by killerham** [aws-amplify/aws-sdk-ios#115]
-objc linker flag causes duplicate symbols. 

I can't get rid of the -objc linker flag since another one of my libraries require it. Is there any way to force_load aws sdk to get this working?

**Comment by fmalekpour** [comment]
I have a heavy app that linked against at least 15 3rd-party library and FrameWorks (Facabook, SoundCloud, CrashReports, Lame, DropBox, Google GTL, Box, etc), all of them need -ObjC flag and AWS is the only one that does not compile with this flag. It's a shame that I have to drop support of import and export from Amazon because of this issue.

**Comment by yosuke-matsuda** [comment]
Which classes do you get duplicate symbols for? You should not use `-force_load` on the AWS SDK. You should force load the libraries that require `-ObjC`. Also, are you using CocoaPods or the frameworks?

**Comment by fmalekpour** [comment]
Bolts, Mantle and basically what this "Framework" needs as dependency. Instead of adding a -force_load for all 15+ libraries and frameworks that I have in my project, I downloaded your source, removed pods support and compiled it as a static library in arm7, arm7s, arm64, i386 and x86_64 and lipo them all together. Took about half an hour but works perfectly fine with -ObjC and does not need to mess with other parts or flags of the project.

**Comment by yosuke-matsuda** [comment]
You can download precompiled frameworks from [AWS Mobile SDK](http://aws.amazon.com/mobile/sdk/). Each third party library is distributed as a separate framework, so you can pick and choose what you need.

**Comment by fmalekpour** [comment]
That's what I did in the first place. Precompiled framework does not work when -ObjC flag is set. With -ObjC flag, if you don't include the 3rd-party frameworks, you get compile error on headers not found. If you include the frameworks, code compiles, but you get duplicate errors in linker.
With static library, all is good and I'm working on integration now.
Thanks.

**Comment by yosuke-matsuda** [comment]
Thank you for bringing the issue to our attention. The AWS Mobile SDK for iOS 2.0.13 and 2.0.14 unintentionally embed the third party libraries  in `AWSiOSSDKv2.framework`. We updated the version of CocoaPods, and the new version adds each pod to **Other Linker Flags**, which resulted in the inclusion of the third party libraries in the main framework.

We've released 2.0.15 to address the issue.

Thanks,
