### ISSUE TITLE
Need source code for libAWSCognitoIdentityProviderASFBinary.a to build specially for tvOS

### ISSUE THREAD

**Issue by gangadharbonda** [aws-amplify/aws-sdk-ios#1178]
I am currently looking for source code which is used for building  libAWSCognitoIdentityProviderASFBinary.a in https://github.com/aws-amplify/aws-sdk-ios/tree/master/AWSCognitoIdentityProviderASF, so I can recompile it specifically for tvOS

As the current library is built only for iOS. Any help on this is greatly appreciated

**Comment by palpatim** [comment]
Hi @gangadharbonda,

I am investigating whether this source code is available and will reply when I have more info.

**Comment by kvasukib** [comment]
@gangadharbonda We have released this source code in the latest release. See https://github.com/aws-amplify/aws-sdk-ios/tree/master/AWSCognitoIdentityProviderASF for further details.

**Comment by bingosabi** [comment]
So I'm pretty sure @gangadharbonda asked for the source code for libAWSCognitoIdentityProviderASFBinary.a which is embedded in the project...      @kvasukib posted a link which goes to the framework wrapper.... not what was asked for or required in order to recompile  libAWSCognitoIdentityProviderASFBinary.a for the tvOS target.    Am I perhaps just not looking in the right place? -> https://github.com/aws-amplify/aws-sdk-ios/tree/master/AWSCognitoIdentityProviderASF

**Comment by bingosabi** [comment]
Ahhh perhaps this was the intended link?   https://github.com/aws-amplify/aws-sdk-
ios/blob/main/AWSCognitoIdentityProviderASF/Internal/AWSCognitoIdentityASF.m

**Comment by bingosabi** [comment]
Disregard... I found the file in Internal and got it to compile.    Sorry for the noise!
