### ISSUE TITLE
AWS connection not established in testflight

### ISSUE THREAD

**Issue by creed360** [aws-amplify/aws-sdk-ios#1180]
I am using Dynamodb, S3 and Facerekognition using ios SDK, all the app works perfect through xcode, but when i install it through testflight, the connection to any of the above 3 is rejected (seen from the log) and the app doesnt work. Any solution?

**Comment by palpatim** [comment]
Hi @creed360,

Sorry to hear you're having problems. Can you provide some more information to help us troubleshoot this with you?

General bug report info:

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:


And a couple more questions:
1. What is the specific error message? (Preferably copy/paste this from the device log.)
1. When use Xcode to get a working installation, are you building from Release or Debug configuration? If Debug, what happens if you build in Release?

**Comment by creed360** [comment]
Thanks for the concern. I was using SDK 2.6.3, i updated my sdk to 2.8.4 and it works fine now both in release and debug mode
