### ISSUE TITLE
Can't implement Facebook registration to Cognito

### ISSUE THREAD

**Issue by gasta-java** [aws-amplify/aws-sdk-ios#1210]
**Environment(please complete the following information):**
 - SDK Version: latest
 - Dependency Manager: Cocoapods
 - Objective C

**Device Information (please complete the following information):**
 - Device: iphoneX
 - iOS Version: [e.g. iOS 12.0]

I get token from Facebook pass it to Cognito but it does not create a user in the user pool. What should I do additionally to create a user?
After getting a token from Facebook I do this code:

```
FacebookProvider *socialProvider = [[FacebookProvider alloc] init];
                    [socialProvider initWithTokens:@{@"graph.facebook.com":result.token.tokenString}];

                    AWSCognitoCredentialsProvider *socialCredentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                                                initWithRegionType:AWSRegionUSEast1
                                                                                identityPoolId:CognitoIdentityUserPoolId
                                                                                identityProviderManager:socialProvider];
                    // Self.socialProvider is that class that implements AWSIdentityProviderManager protocol

                    AWSServiceConfiguration *fbConfiguration = [[AWSServiceConfiguration alloc]
                                                                initWithRegion:AWSRegionUSEast1 credentialsProvider:socialCredentialsProvider];
                    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = fbConfiguration;

                    //create a pool
                    AWSCognitoIdentityUserPoolConfiguration *configuration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:CognitoIdentityUserPoolAppClientId  clientSecret:CognitoIdentityUserPoolAppClientSecret poolId:CognitoIdentityUserPoolId];

                    [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:fbConfiguration userPoolConfiguration:configuration forKey:@"UserPool"];

                    AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];

                    pool.delegate = self;

                    NSLog(@"socialCredentialsProvider.getIdentityId: %@", socialCredentialsProvider.getIdentityId);
```

I struggled with implementing of the Facebook registration to Cognito a week already. Maybe can you provide a working example project on ObjC or SWIFT with that?

**Comment by rohandubal** [comment]
Hello @gasta-java 

The issue here is that you are trying to use 2 different services for the use-case. When you provide the Facebook token in logins map with `graph.facebook.com` it created an identity in `Cognition Federated Identity` service and NOT `Cognito UserPool Service`. 

To create a Facebook user in `Cognito UserPool Service`, currently the only way is to use the `AWSCognitoAuth` SDK which is hosted auth SDK where the user can sign in via Facebook. If that flow is used, there will be a user created in `Cognito UserPool`. 

The current approach will give you authenticated AWS Credentials via federation with Facebook. Please let me know if this explains the issue. If you are unable to achieve your use-case, please let me know and I can help you with appropriate documentation.

Thanks,
Rohan
