### ISSUE TITLE
[Auth] Authenticate requests to Pinpoint with Authenticated Cognito Identities

### ISSUE THREAD

**Issue by returnzer0** [aws-amplify/aws-sdk-ios#1218]
**Describe the bug**
I want to update the endpoint of a user in swift code, I am copying the sample code from amplify docs and am trying to update their endpoint to APNS but it gives me the following error.

```
Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=0 "MissingAuthenticationTokenException" UserInfo={responseStatusCode=403, message=Missing Authentication Token, responseHeaders=<CFBasicHash 0x6000022b2140 [0x1153c7b68]>{type = immutable dict, count = 10,
entries =>
	0 : X-Cache = <CFString 0x6000037fcb40 [0x1153c7b68]>{contents = "Error from cloudfront"}
	1 : Content-Type = <CFString 0x6000037c70c0 [0x1153c7b68]>{contents = "application/json"}
	2 : x-amzn-ErrorType = <CFString 0x600002282140 [0x1153c7b68]>{contents = "MissingAuthenticationTokenException"}
	3 : x-amzn-RequestId = <CFString 0x600002281f40 [0x1153c7b68]>{contents = "f83e0b4f-2aba-11e9-9e54-5561585be9a4"}
	4 : Via = <CFString 0x600001ca8c60 [0x1153c7b68]>{contents = "1.1 2d845616bb025756fb00e75135987ac7.cloudfront.net (CloudFront)"}
	5 : x-amz-apigw-id = <CFString 0x6000037c6e80 [0x1153c7b68]>{contents = "UuQZwEg4IAMFhhA="}
	6 : Date = <CFString 0x6000037c7120 [0x1153c7b68]>{contents = "Thu, 07 Feb 2019 09:30:12 GMT"}
	10 : Content-Length = 42
	11 : X-Amz-Cf-Id = <CFString 0x600001b480f0 [0x1153c7b68]>{contents = "5C6wbIQ3jTHTvVtJnLwhPF4lxNTTqTuCO07IyDpRANMd_ZZ9rlZvXg=="}
	12 : Connection = <CFString 0x600003831560 [0x1153c7b68]>{contents = "keep-alive"}
}
, responseDataSize=42, NSLocalizedFailureReason=MissingAuthenticationTokenException}
```

This is what my swift request code looks like:

```
if let targetingClient = myDelegate.pinpoint?.targetingClient {
                let endpoint = targetingClient.currentEndpointProfile()
                
                // Create a user and set its userId property
                let user = AWSPinpointEndpointProfileUser()
                user.userId = "abc123"
                // Assign the user to the endpoint
                endpoint.user = user
                print("Channel type: \(endpoint.channelType)")
                // Update the endpoint with the targeting client
                targetingClient.update(endpoint).continueWith { (task) -> Any? in
                    if let err = task.error {
                        print("Error \(err)");
                    } else {
                        print("Success \(task.result)")
                    }
                    
                    return nil
                }
                
                
                print("Assigned user ID \(user.userId ?? "nil") to endpoint \(endpoint.endpointId)")
            }
```

I have set up this app with the Cognito configuration as well, I am able to add channelType: email to the endpoints, but not APNS.

**Which AWS service(s) are affected?**
AWS Pinpoint

**Expected behavior**
I should be able to update endpoints without errors.

**Environment(please complete the following information):**
 - SDK Version: latest
 - Dependency Manager: CocoaPods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - iOS Version: iOS 11.0
 - Specific to simulators:

**Comment by returnzer0** [comment]
I think the problem is that I am not using AWSMobileClient to setup pinpoint inside AppDelegate. I would prefer not to use it, is there a way that I can Authenticate pinpoint without the use of AWSMobileClient?

**Comment by returnzer0** [comment]
Trying to initialize MobileClient but I get the following error:

`Static member 'initialize' cannot be used on instance of type 'AWSMobileClient`

**Comment by returnzer0** [comment]
I am using AWSMobileClient for setting up now, I get a similar error to #1216.

This is how I set up my pinpoint configuration instead. Users are able to log in via MobileClient but I still get the same error as above.

```
        /** start code copy **/
        // Create AWSMobileClient to connect with AWS
        AWSMobileClient.sharedInstance().initialize { (userState, error) in
            if let error = error {
                print("Error initializing AWSMobileClient: \(error.localizedDescription)")
            } else if let userState = userState {
                print("AWSMobileClient initialized. Current UserState: \(userState.rawValue)")
            }
        }
        
        
        // Initialize Pinpoint
        let pinpointConfiguration = AWSPinpointConfiguration.init(appId: pinpointAppId, launchOptions: launchOptions)
        pinpoint = AWSPinpoint(configuration: pinpointConfiguration)
        
        /** end code copy **/
```

**Comment by rohandubal** [comment]
Hello @returnzer0 

Does your `awsconfiguration.json` look like this:

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:xxxxxxxxxxx-7c8b-425f-91c9-xxxxxxxxxxx",
                "Region": "us-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-west-2_XXXX",
            "AppClientId": "xxxxxxxxxxx",
            "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "us-west-2"
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "YOUR_PINPOINT_APP_ID",
            "Region": "us-east-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "us-east-1"
        }
    }
}
```

Do you have an approximate timestamp for the above `requestId` which you have posted? I am checking with the service team as well to determine if there is some issue.

Thanks,
Rohan

**Comment by returnzer0** [comment]
Hi @rohandubal, I was missing the 

```
"CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:xxxxxxxxxxx-7c8b-425f-91c9-xxxxxxxxxxx",
                "Region": "us-west-2"
            }
        }
    }
```

snippet. 


I am only using Cognito User Pools, not identity pools. If I set it up using this awsconfiguration.json file it gives me an error. Do I need to set up an identity pool?

**Comment by kvasukib** [comment]
@returnzer0 Thank you for the response. You need a CredentialsProvider which either uses Access/Secret Access Key (long-lived AWS Credentials) or Cognito Identity Pool id (short-lived AWS Credentials) in order to sign the request to Pinpoint.

So with the solution @rohandubal proposed, you would need 
```
"CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:xxxxxxxxxxx-7c8b-425f-91c9-xxxxxxxxxxx",
                "Region": "us-west-2"
            }
        }
    }
```

in your awsconfiguration.json file. You need to configure Cognito Identity Pool on your backend either using Amazon Cognito console or amplify-cli. Once it is configured, if you use the `awsconfiguration.json`, the CredentialsProvider will be constructed using the `CredentialsProvider` snippet and then you can integrate it with Pinpoint.

Cognito Identity -> `awsconfiguration.json` -> `AWSMobileClient` -> `AWSPinpoint.TargetingClient`

Let me know your thoughts on this.

**Comment by returnzer0** [comment]
Hi, @kvasukib. Thanks for your reply.

If I want to provide long-lived credentials. How would I go about doing that? I think, I can create an IAM Role and attach policies to it, and then provide the access/secret key via the iOS app. Something that I think isn't very safe. Is there a safer alternative?

If I were to go with short-lived credentials (Cognito Identity), does that mean I will have to use `AWSMobileClient` or could I use the `AWSCognitoIdentityProvider` sdk instead?

Right now, my entire login flow is connected with `AWSCognitoIdentityProvider` that's the reason I would like to stick with it.

Looking forward to your reply. Thanks

**Comment by kvasukib** [comment]
@returnzer0 Thank you for the detailed response.

I recommend you to use Amazon Cognito Federated Identities as that provides short-lived credentials. You can use either `AWSMobileClient` or `AWSCognitoIdentityProvider`.

If you use `AWSCognitoIdentityProvider`, you have to manage federation of the token into the `AWSCognitoCredentialsProvider` in order to get an identity.

However, if you use `AWSMobileClient`, it automatically federates the token and retrieves the Cognito Identity and AWSCredentials in order to make the sign the AWS requests.

**Comment by returnzer0** [comment]
@kvasukib No worries, thanks for your patience as well :)

If I want to go with the `AWSCognitoCredentialsProvider` route, are there any code examples that you could share so that I can set up pinpoint? As mentioned before, I am at a state where moving to `AWSMobileClient` will be too much work, so I am trying to avoid it if possible.

**Comment by kvasukib** [comment]
@returnzer0 Sorry for the delayed response. I would still recommend using `AWSMobileClient` as it does the federation for you automatically. To answer your question specifically:

`AWSCognitoCredentialsProvider` is an object that retrieves the credentials from Amazon Cognito and supplies credentials to sign the requests to AWS (for example to upload file to S3).

`AWSCognitoIdentityProvider` object in the SDK provides the abstraction for Amazon Cognito UserPools and helps you sign-in a user and retrieve the tokens that proves that the user is authenticated.

When a user is signed-in and `AWSCognitoIdentityProvider` has retrieved the tokens from Amazon Cognito UserPools, the tokens can be federated into the `AWSCognitoCredentialsProvider` in order to retrieve AWSCredentials and Cognito Identity Id for this authenticated user. To do so, you need to supply the token in the logins map and pass the logins map to `AWSCognitoCredentialsProvider`.

To accomplish this, you need to 

1) create a class that confirms to the `AWSIdentityProviderManager` protocol and implements the `logins` method that returns a map of { providerLoginKey -> token }. 

```
@interface AWSFederationManager : NSObject<AWSIdentityProviderManager>

@property (nonatomic, readonly, strong) AWSCognitoCredentialsProvider *credentialsProvider;

@end
```

```
@interface AWSFederationManager()

@property (nonatomic, readwrite, strong) AWSCognitoCredentialsProvider *credentialsProvider;

@end
```

```
@implementation AWSFederationManager

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
        return [AWSTask taskWithResult:@{[<identityProviderName> : <token>}];
}

@end
```

2) Set the delegate of the `AWSCognitoCredentialsProvider` object to the class created in step (1).

```
@implementation AWSFederationManager

- (instancetype) initialize {
    [self.credentialsProvider setIdentityProviderManagerOnce:self];
}

@end
```

Now once the federation is successful, you will be able to retrieve the AWSCredentials and Cognito Identity Id.

You can refer [Source](https://github.com/aws-amplify/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSAuthCore/AWSIdentityManager.m#L58) for the reference implementation. 

Please let me know if you have any questions.
