### ISSUE TITLE
_serviceClients never removes the key once we call AWSS3TransferUtility.remove(forKey: key)

### ISSUE THREAD

**Issue by pablogeek** [aws-amplify/aws-sdk-ios#1242]
**Describe the bug**
Even if we remove the transfer utility it won't delete the key from serviceClients. So basically it won't work if you try to create another AWSTransferUtility with the same key later 
**To Reproduce**
Register AWSS3TransferUtility.register and then AWSS3TransferUtility.remove

**Which AWS service(s) are affected?**
AWS S3
**Expected behavior**
_serviceClients should delete that key when  `AWSS3TransferUtility.remove` is called

**Comment by cbommas** [comment]
@pablogeek 

The key is actually removed, but it is done in the `didBecomeInvalidWithError` callback after the underlying NSURLSession is properly closed. This process is asynchronous, so if you remove and add the TransferUtility using the same key in rapid succession, you can get errors due to timing issues. 

The best practice here is to register the TransferUtility as early as possible in one of the app lifecycle methods and remove it ( if you need to) as late as possible in an app lifecycle method.
 
https://github.com/aws-amplify/aws-sdk-ios/blob/dc45a0d0c4c379abfc2c1122d3ff2c3df0febd35/AWSS3/AWSS3TransferUtility.m#L1924

**Comment by pablogeek** [comment]
@cbommas Thanks for your response. We use different AWS configuration for each upload, we got different keys from Backend. So I can't register the `AWSS3TransferUtitlity` at startup. There are a few cases where it won't enter to this method after removing the `AWSS3TransferUtitlity` The problem I had was clearly not a timing issue.

**Comment by cbommas** [comment]
@pablogeek 
That is interesting. I did a little more digging on this topic and here are my findings
 - the call to `register` does not check to see if the key already exists and will overwrite a client object that was previously registered. 
- the `didBecomeInvalidWithError` callback is invoked by NSURLSession, once the session has been properly closed. 

Can you share the error message you were getting?
