### ISSUE TITLE
Compile error in AWSUICKeyChainStore.h when compiling with -Werror,-Wobjc-property-no-attribute

### ISSUE THREAD

**Issue by aaronetz** [aws-amplify/aws-sdk-ios#1255]
I'm building an internal library on iOS that uses AWSCore.Framework. I'm using the latest version of the SDK (2.9.1). There is compile error in one of the files (we have all warnings enabled and warnings as errors):

`AWSCore.framework/Headers/AWSUICKeyChainStore.h:120:1: error: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
@property (nonatomic, nullable) NSString *authenticationPrompt`

Adding the `strong` attribute fixed the issue for me. I'm not familiar with the internals of the SDK so I'm not sure if that is the correct fix.

**Comment by kvasukib** [comment]
@aaronetz Sorry for the inconvenience caused. We will take a look at it. Thank you!

**Comment by palpatim** [comment]
I'm reluctant to change this for a couple of reasons:

1. The message is being reported on a [third party library](https://github.com/kishikawakatsumi/UICKeyChainStore) we forked and brought into the AWSCore code as source. That library has [not changed that property declaration](https://github.com/kishikawakatsumi/UICKeyChainStore/blob/master/Lib/UICKeyChainStore/UICKeyChainStore.h) in the intervening time since we forked.
1. The message involves ownership semantics on a CF bridged property, and I'm not sure that `strong` is actually the correct value to use for this. I agree that `strong` is the default if the class is under ARC, so in theory it should be an innocuous change. However I'm concerned there may be some settings somewhere that I'm not aware of that override that. (IIRC, the default for MRC is `weak` or `assigned`, so if there is some flag that removes the UICKeyChainStore classes from ARC, then it wouldn't default to `strong` any more and adding specifier would be inappropriate.)

At this point, since this is a warning rather than a verifiable error, and since it's in 3p code that we're unfamiliar with, we're not going to change this.
