### ISSUE TITLE
AWSS3TransferUtility cancel closure

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/aws-sdk-ios#1312]
**State your question**
It seems that cancelling an upload task does not call the completion handler closure. Is there a way to get the closure called with specific error describing a cancellation ?

**Which AWS Services are you utilizing?**
Cognito, S3

**Provide code snippets (if applicable)**
```
transferUtility.uploadData(data, key: key, contentType: contentType, expression: expression) { (task, error) in
    if let error = error {
        // error, not called when cancelled
    }
    else {
        // success
    }
}.continueWith { (task) -> Any? in
    if let result = task.result {
        delay(2)
        result.cancel()
    }
})
```
**Environment(please complete the following information):**
 - SDK Version: 2.8.4
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Comment by cbommas** [comment]
@ryancrunchi 
That is the current behavior across upload, multipart upload and download i.e., when the task is cancelled, it does not call the completion handler.

I have marked this as a feature request and we will provide an update when we have been able to establish a timeline for this.

**Comment by modibhaviks** [comment]
There is no specific closure available for Cancel event but we can manage it by handling error with following approach:

https://github.com/aws-amplify/aws-sdk-ios/issues/932#issuecomment-494749973

**Comment by lawmicha** [comment]
@modibhaviks thanks for letting us know the approach you taking to have the completionHandler called for cancelled task which also have an error. To summarize the feature request, as a developer i want to be able to be notified of the completion of a cancelled task through a callback mechanism so that I can control the outcome of a failed cancellation.

Another note, I don't think the error that is being swallowed by the return statement is an error for the cancellation (but it could be). The task may have gotten an error during the transfer, and as it was being processed before calling the completionHandler with error, an cancellation by the user had occurred so the checking for cancelled task and returning immediately is dropping the error.

Recap on current behavior; in the scenario where the user action triggers the cancellation, completionHandler does not get called on any errors (errors due to on-going transfer or cancellation of the task). 

If we introduce always calling the completion handler on errors, then the developer will get to decide what behavior to have, either provide a visual for the end user or swallow the error if the task is already cancelled.

To better understand this scenario, what kind of errors are you receiving on failed cancellations with the workaround? is it specific to the cancellation failing?

**Comment by lawmicha** [comment]
I have added a task to our backlog. as part of that, we will identify the scenarios which result in cancellation errors so that we can make the decision on whether they should or should not be returned on the completionhandler.

**Comment by atierian** [comment]
This appears to be resolved through returning the task post cleanup. If this is still an issue for you, please comment here and we'll reopen. Thanks.
