### ISSUE TITLE
Wrong error message on signIn (2.9.6)

### ISSUE THREAD

**Issue by N1LaT** [aws-amplify/aws-sdk-ios#1495]
**Describe the bug**
When adding a user to the user pool and aborting the app during verification, the user is added but in unconfirmed state. When I try to log in afterwards with "signIn" Method, I receive a "userNotFound" error instead of an "userNotConfirmed" error.

**To Reproduce**
1. Sign up on userpool
2. Do NOT authenticate user
3. Try to login with user

**Which AWS service(s) are affected?**
AWSMobileClient 2.9.6

**Expected behavior**
userNotConfirmed error should be thrown

**Environment(please complete the following information):**
 - SDK Version: 2.9.6
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information (please complete the following information):**
 - Device: iPhone6s
 - iOS Version: latest

**Comment by palpatim** [comment]
@N1LaT Thanks for reporting this. 

1. Are you able to view the user in your user pools console? If so, does the "Account status" properly report an unconfirmed state?
1. Does this happen even if you completely reset the simulator (or device) on which you're running the app? Such a reset would clear any stored credentials from the keychain and would help us rule out whether we're incorrectly retrieving stored state.

**Comment by N1LaT** [comment]
Good morning.

Ad 1) Yes, the user is in the userpool. I added a picture.
Ad 2) I deleted the app, and used an Email I haven't used before so this should do it. 

Still receiving userNotFound :-(
No idea why the console says aws-sdk-ios-2.9.3 because the pods installed are 100% 2.9.6 and have been 2.9.4 before.
![1](https://user-images.githubusercontent.com/48475255/56641387-947df400-6675-11e9-8fc7-f4f09bc8cb63.png)

**Comment by N1LaT** [comment]
Short update, I tried to bypass the error by adding the user to my dynamo db with an "is_authorized" flag and check that before doing a login.
And if I do a login and get a .userNotFound error and the "is_authorized" flag is not set then trying to call resendSignUpCode, but then I unfortunately get an error as well, saying: "Username/client id combination not found", so this is not possible unfortunately.
Seems that I have to wait on a pod update on this....

**Comment by N1LaT** [comment]
Any news or a designated fixed version yet?

**Comment by N1LaT** [comment]
Guys... this ticket is almost 2 months old. Is it fixed yet or still not? A quick update would be very appreciated.

**Comment by royjit** [comment]
Hi @N1LaT  Apologies for the delayed response.

I tried to replicate the issue and I am not able to reproduce the issue. Could you please provide us the following details:

1. Are you using the same user name for signUp and signIn operation? 
2. Were you trying to login using the email address?
3. What settings you have enabled under the section "How do you want your end users to sign in?" in your Cognito user pool console under attributes

**Comment by royjit** [comment]
Are you trying to use an email to signIn for an unconfirmed user? 

If you have signed up a user with `username` and gave `email` as user attribute, you will get `userNotConfirmed` if you signIn with `username` and `password` and you will get `userNotFound` if you signIn with `email` and `password`. 

We are actively working on this to see if we can provide appropriate error message in both cases. We will post an update as soon as we have more information.

**Comment by royjit** [comment]
Looks like this is the intended behavior of Cognito User pool. If you configure a user pool with usernames and also allow users to sign in with email addresses (and/or phone numbers), the email (or phone) can only be used to sign in once it has been verified. The email/phone becomes an active "alias" for the user once it is verified. 

Because of this limitation that an unverified email/phone can't be used, and because in many cases, you don't need/want a username that's separate from the email address, Cognito added a second option for User Pools where you don't provide a separate username and email address value (you only provide email) on sign up, and the email address is immediately attached to the user and can be used to attempt sign in when the account is unconfirmed and the email is not verified.

You can read more in the Cognito Developer Guide: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings

Closing this issue as there is no response. Feel free to reopen if you have more questions.
