### ISSUE TITLE
S3 AWSS3TransferUtilityUploadExpression callback twice

### ISSUE THREAD

**Issue by daveleenew** [aws-amplify/aws-sdk-ios#1529]
**Describe the bug**

S3 AWSS3TransferUtilityUploadExpression callback twice

<NSProgress: 0x600002ccc780> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 316481 of 316481  
<NSProgress: 0x600002ccc780> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 316481 of 316481  

**To Reproduce**

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by palpatim** [comment]
@daveleenew 

Can you help us troubleshoot by providing some more detail? Is this happening on uploads of any size, or only if they fall above/below a certain threshold? What version of the SDK are you using? Can you post a code snippet with your expression?

**Comment by daveleenew** [comment]
/// upload progress
        let expression = AWSS3TransferUtilityUploadExpression()
        
        expression.progressBlock = {(task, progress) in
         
///callback twice when progress.fractionCompleted = 1.0
)}

**Comment by daveleenew** [comment]
https://stackoverflow.com/questions/39051473/amazon-s3-uploading-twice

@palpatim

**Comment by lawmicha** [comment]
Hi @daveleenew 

Thanks for reporting the issue, I took a look at the SO question and the update said that it was due to the first upload failing. 

Can you enable some more verbose logging and let us know if you can determine what is happening?

Enable verbose logging from the SDK to the console output https://aws-amplify.github.io/docs/ios/manualsetup#logging
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        AWSDDLog.sharedInstance.logLevel = .verbose
        AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
        
        // Other set up, etc..
        AWSMobileClient.sharedInstance().init..
        AWSS3TransferUtility.register..
        return true
    }
```

I want to clarify, 
- is it two uploads going on at the same time? 
- are you getting two sets of progress events? ie. double 0 to 100 progress events 
- or are you just getting a single 100% progress event, twice?
- Is this happening on uploads of any size, or only if they fall above/below a certain threshold? 
- What version of the SDK are you using?
