### ISSUE TITLE
Migrate S3 SDKs to use virtual-hosted (V2) style URLs

### ISSUE THREAD

**Issue by Mazyod** [aws-amplify/aws-sdk-ios#1535]
**Describe the bug**
Dispatching an S3 request with AWSS3 SDK uses V1 path-style URL. This style is going to be dropped next year. https://forums.aws.amazon.com/ann.jspa?annID=6776

**To Reproduce**
1. Initialize an AWSS3 request.
2. Dispatch the request.
3. Notice the URL being dispatched.

**Which AWS service(s) are affected?**
S3

**Expected behavior**
URL should be virtual-hosted style V2 instead.

**Environment(please complete the following information):**
 - SDK Version: 2.9.7
 - Carthage
 - Swift Version : 5.0.1

**Comment by palpatim** [comment]
@Mazyod Thanks for pointing this out. We'll add it to our backlog and plan on rolling it out well in advance of the deadline so customers have time to migrate.

**Comment by joduss** [comment]
I would like to know if an update is planned.
The path-style API requests will be deprecated in 2 months!

**Comment by palpatim** [comment]
Hi all, this should be fixed with the [2.17.0](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.17.0) release. If you pin to a particular version of the SDK, please update your Podfiles to point to at least `~> 2.17.0`.

Please note that this release includes a couple of breaking changes, one directly related to supporting virtual-host style URL addressing for S3. It won't affect most customers, since the primary configuration method is to use `awsconfiguration.json` or `amplifyconfiguration.json` files to configure the SDK. However, if you manually configure the SDK, please do review the release notes for a detailed discussion of the new URL normalization rules that the SDK applies.

Please let us know if you have any questions.
