### ISSUE TITLE
Completion Handler not called when device goes offline during upload task

### ISSUE THREAD

**Issue by rishabh-latfire** [aws-amplify/aws-sdk-ios#1656]
**Description**
During an upload using TransferUtility If I put my phone on offline mode the transfer stops with out any errors. No completion handler is called either.
I saw a related issue where it was suggested to use `transferUtilityConfiguration.timeoutIntervalForResource ` but in that case the request times out even on successful connection if the file is too big to be upload in the given time period.
Although the task resumes if I switch on my connection later, what I want is to cancel the task and show an error ( If the device goes offline)
Additionally, I also tried using `AWSServiceConfiguration.timeoutIntervalForRequest`, but it doesn't seem to be doing anything.
I'm new to using this service, and perhaps I'm making some trivial error. Any help is appreciated.

**To Reproduce**
Put the device in offline mode during an upload task.

**Which AWS service(s) are affected?**
AWSTransferutility

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version :4.0

**Device Information (please complete the following information):**
 - Device: Iphone6, Iphone XR( Simulator)
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

`

**Comment by rishabh-latfire** [comment]
Code I am Using:
		`let region = AWSRegionType.regionTypeForString(regionString: regionString)

		let credentialsProvider = MTCredentialsProvider(accessKey: accessKey,
		                                                secretKey: secretKey,
		                                                sessionToken: sessionToken)
		let configuration = AWSServiceConfiguration(
			region: region,
			credentialsProvider: credentialsProvider)
		AWSServiceManager.default().defaultServiceConfiguration = configuration
		configuration?.timeoutIntervalForRequest = 5
		configuration?.maxRetryCount = 1
		awsResourceIdentifier = uploadingRequestUniqueKey()
		guard let resourceIdentifier = awsResourceIdentifier else {
			return
		}

		let transferUtility = AWSS3TransferUtility.default()

		transferUtility.uploadData(
			data,
			bucket: S3BucketName,
			key: resourceIdentifier,
			contentType: contentType,
			expression: expression,
			completionHandler: completionHandler).continueWith { task -> Any? in
			if let error = task.error {
//
			}

			if let uploadTask = task.result {
//
				}`

**Comment by palpatim** [comment]
@rishabh-latfire 

I believe you are seeing expected behavior. TransferUtility queues uploads in the background specifically so it can process them reliably in all kinds of conditions: while the app is in the foreground, while it is in the background, or if the network drops. As such, only fatal conditions (such as a timeout) would trigger the completion handler because by definition, the transfer isn't yet complete.

If you're interested in detecting no-network conditions, you could use something like Apple's [SCNetworkReachability framework](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability-g7d) to monitor the network. However, this is not a recommended practice for a number of reasons, one of the primary being: Especially in mobile use cases, network connectivity is inherently unreliable, and reacting to network changes can lead to "thrashing" behavior as you preemptively try to respond to a network situation that will often resolve itself. The recommended practice is to attempt network calls and deal with failures if/when they occur.

In this case, I would guess that displaying errors on every detection of a bad network situation would quickly become tiring for users, since they'd see errors every time they pass in and out of low/bad network conditions, and would then be forced to re-queue their uploads. Perhaps what you are trying to do is advise the user of an upload's progress? In that case, you can use the uploadExpression to report overall progress of a resource, and do something subtle like change the upload progress UI to indicate a bad network, and reserve failure conditions for an actual failure.

`AWSServiceConfiguration.timeoutIntervalForRequest` would not be applicable to a TransferUtility upload; the `TransferUtilityConfiguration.timeoutIntervalForResource` is the correct API to control timeouts on TU operations.

Hope this helps.
