### ISSUE TITLE
AWSMobileClient initialize{} and addUserStateListener{} return different `userState`

### ISSUE THREAD

**Issue by Skifcha** [aws-amplify/aws-sdk-ios#1669]
**Describe the bug**
I'm using AWSMobileClient only for Cognito authentication.
I've went through manual installation, so I have my awsconfiguration.json file and this is the only code I use for initialization:
```
AWSMobileClient.sharedInstance().initialize { (userState, error) in
    if let userState = userState, userState == .signedIn {
        self.updateAWSCredentials()
        return
    }

    DispatchQueue.main.async {
        self.signOut()
    }
}
```

awsconfiguration.json file:
```
{
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-west-2:...",
                "Region": "us-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "...",
            "AppClientId": "...",
            "Region": "us-west-2"
        }
    }
}
```

I have no issues with sign in / sign up, it works just great.
For signed in users I also refetch tokens with `AWSMobileClient.sharedInstance().getAWSCredentials` method on every app launch.
```
func updateAWSCredentials(_ completion: ((Error?) -> Void)? = nil) {
    AWSMobileClient.sharedInstance().getAWSCredentials { (credentials, error) in
        self.AWSCredentials = credentials
        completion?(error)
    }
}
```

But if the app stays untouched for some time (week or more), on the next app launch method `AWSMobileClient.sharedInstance().initialize` returns `.signedIn` and `AWSMobileClient.sharedInstance().addUserStateListener` returns `.signedOutUserPoolsTokenInvalid`.
**Also at the same time `AWSMobileClient.sharedInstance().getAWSCredentials` callback never being called.**
The last one actually bothers me much more, because my app is waiting for response of this method and basically stays empty forever.

**To Reproduce**
1. Keep the app untouched for some time (in my case week or so is enough). You probably can manipulate with Simulator date to reproduce time gap.
2. Launch the app
3. Check user state inside `AWSMobileClient.sharedInstance().initialize` and `AWSMobileClient.sharedInstance().addUserStateListener` methods
4. Method `initialize {}` returns `.signedIn`, `addUserStateListener {}` returns `.signedOutUserPoolsTokenInvalid`
5. Callback of `AWSMobileClient.sharedInstance().getAWSCredentials` never being called

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
Both methods should throw the same states also `AWSMobileClient.sharedInstance().getAWSCredentials` callback should be called at least with error.

**Environment(please complete the following information):**
 - SDK Version: 2.10.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 7, Simulator iPhone XS Max
 - iOS Version: iOS 12.1-12.1.3

**Comment by palpatim** [comment]
@Skifcha 

We believe we understand the root cause of this and have put it in our queue to fix. We're tracking that issue on #1686 and will update it once it's finished.

Since you are reporting slightly different reproduction steps, it's possible that you're encountering a different issue (although I don't think so). Therefore, I'm going to leave this issue open so you can verify it separately once we get a fix in for #1686.

**Comment by Skifcha** [comment]
@palpatim ok, thanks!

**Comment by palpatim** [comment]
An update:

The race condition is more difficult to resolve than we originally thought, but we are continuing to work on it. In the meantime, @royjit has merged #1815, which fixes an error where signIn and confirmSignIn callbacks would sometimes not be called. That resolves #1686, but will not address the race condition we believe is at the heart of this issue.

We'll update this issue when we have more information.

**Comment by vin047** [comment]
I'm experiencing this same issue but with Federated sign-in instead of Cognito User pools.

`AWSMobileClient.sharedInstance().initialize` gives UserState as `signedIn`, but when using TransferUtility to download a file, `AWSMobileClient.sharedInstance().addUserStateListener` gives UserState as `signedOutFederatedTokensInvalid`.

> If you let the user to signIn at this point, AWSMobileClient.sharedInstance().getAWSCredentials should continue as normal.

After I get the `signedOutFederatedTokensInvalid`, I invoke `AWSMobileClient.sharedInstance().federatedSignIn` which signs in the user and it's callback gives `signedIn` as expected. However, TransferUtility does not try to resume the download, neither does it call the callback with an error. As @Skifcha stated, this is an even bigger issue than the inconsistency between `initialize` and `addUserStateListener` as we are unable to develop retry logic - short of implementing a timeout for the callback to return. 

Any insight into this @royjit?

**Comment by Skifcha** [comment]
@royjit Hey, I'll check on Monday and let you know.

**Comment by Skifcha** [comment]
@royjit yep, it's the same as @vin047 said. So different states are (kinda) fine, but callback from `getAWSCredentials` in my case is never called - that's the real issue. Eeven if I get valid state from `login state listener` method, the only way to fix frozen response from `getAWSCredentials` is to completely sigh out and and sign in again.

**Comment by vin047** [comment]
Some more info to add:

1. `initialize` and `addUserStateListener` return different states (`signedIn` and `signedOutFederatedTokensInvalid`). This causes the SDK to refresh the tokens when a service is accessed - if they were the same (e.g. both `signedOutFederatedTokensInvalid`) the listener would not be fired, meaning the logic to call sign-in again would not work. I'm not sure if this behaviour is intentional or not.

2. The more serious issue of the callbacks not firing even after successfully refreshing sign-in is due to the `AWSTask` created from the SDK never actually starting - in my case, I'm using:

```swift
transferUtility.download(to: url, bucket: bucket, key: key, expression: nil) { _, localURL, _, error in
    // THIS BLOCK IS NEVER CALLED
}
```

but when I chain a `continueWith` block at the end, i.e.

```swift
transferUtility.download(to: url, bucket: bucket, key: key, expression: nil) { _, localURL, _, error in
    // THIS BLOCK IS NEVER CALLED
}.continueWith { task -> Any? in
    if let error = task.error {
        print(error.localizedDescription)
    }
    if let result = task.result {
        print("started")
    }
    return nil
}
```

The `continueWith` block is always called, even after refreshing sign-in. **However, the task always returns an error:** `Obtaining an identity id in another thread failed or didn't complete within 5 seconds`. Since the task always returns with an error, it never starts the actual download task, which is why the download callback block is never executed. From the error message, I'm convinced that this issue is the same as #1519.

This might be the same issue for @Skifcha too - despite successfully refreshing sign-in, `getAWSCredentials` must be failing to get the identity id. Unfortunately, as it does not return an `AWSTask`, they're unable to see the error or handle it and the callback is never executed - because the underlying "task" has an error. (Pure conjecture, I've no idea how `getAWSCredentials` actually works under the hood).

**Comment by deter3** [comment]
I installed amplify auth , removed and reinstalled . I came across "Failed to authenticate request. Error: notSignedIn(message: \"User is not signed in, please sign in to use this API" when AWSMobileClient.sharedInstance().isSignedIn says the state is true . But my cognito is empty  and  AWSMobileClient.sharedInstance().identityId is nil . 

My solution is 

`if AWSMobileClient.sharedInstance().isSignedIn && AWSMobileClient.sharedInstance().identityId != nil {
print("we singed in ")
}else{
AWSMobileClient.sharedInstance().signOut()
AWSMobileClient.sharedInstance().showSignIn(navigationController: navigationController!) { (userState, error) in
                guard error == nil else {return }
                guard let state = userState else {return}
                if state == .signedIn{
                    print("singed in ")
}`

By doing so , I can push the controller of "sign in " and allow new users being added into cognito . Then everything is fine .

**Comment by royjit** [comment]
We made a lot of improvements in AWSMobileClient in the release 2.11.0 of the SDK. Could you please verify that your issue is fixed with the latest SDK? https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.11.0

Please reach out if you still facing problems with the SDK.

**Comment by Skifcha** [comment]
@royjit will check, thanks.
