### ISSUE TITLE
FABKitProtocol.h file not found while compiling AWSCognitoIdentity+Fabric.m

### ISSUE THREAD

**Issue by slootzky** [aws-amplify/aws-sdk-ios#1777]
**Describe the bug**
Getting this error in build time.
I'm using Fabric 1.6.13
and AWSAPIGateway 2.6.35

**Environment(please complete the following information):**
 - SDK Version: AWSAPIGateway (2.6.35)
 - Dependency Manager: Cocoapods 1.7.3
 - Swift Version : 4.2
 - Xcode : 10.1

**Device Information (please complete the following information):**
 - Device: Simulator Iphone X
 - iOS Version: iOS 12.1

**Additional context**
Also tried doing this in pod post_install script :

```
installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['USER_HEADER_SEARCH_PATHS'] = '"${PODS_ROOT}/AWSCore/AWSCore/Fabric"'
          config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'Yes'
```

but with no luck.
This is a react-native ios application

**Comment by slootzky** [comment]
help?

**Comment by slootzky** [comment]
Hey, 
although my app is React-Native, I think we can ignore this because issue is pure native (IMHO).
I finally hunted down the issue and managed to reproduce it easily.
Issue shows up whenever there's Branch.io and AWSCore in the same project.
I've created a new example app to reproduce it (simple swift ios app and added branch via npm).
instructions are in the ReadMe

[app](https://github.com/slootzky/AwsBranchIssue)

**Comment by benkraus** [comment]
We are experiencing a similar issue. We can't use the `amplify-js` package, as it doesn't support client secrets. Thus, we use the native iOS SDK which does.

However, when using both the native iOS SDK and the Branch library, conflicts arise as both copy some of the Fabric headers. 

Here's a related issue: https://github.com/aws-amplify/aws-sdk-ios/issues/351

Our workaround was to turn on the legacy build system for our workspace, and use that above `post_install` step to get things working. It doesn't look like we can migrate off the Legacy build system though because of this issue.

**Comment by benkraus** [comment]
(@slootzky have you tried enabling the legacy build system?)

**Comment by benkraus** [comment]
I would also call out that this would also be an issue in a standard native app, not localized to a React Native app. So "use the amplify js lib" wouldn't solve anything here.

**Comment by slootzky** [comment]
@benkraus yeah , tried to enable legacy build and it didn't help.
eventually - upgrading branch.io version to v3.1.1 solved the issue for me.

**Comment by palpatim** [comment]
@slootzky Thanks for confirming that upgrading to the latest version of branch.io solved your issue.
