### ISSUE TITLE
AWS iOS SDK closure not called

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/aws-sdk-ios#1835]
**Describe the bug**
Using the latest iOS SDK (2.10.3), there are two functions where the closure is not called: 

• AWSMobileClient.sharedInstance().getTokens({ (tokens, error) in ...

• AWSMobileClient.sharedInstance().signIn(username: email, password: password) { (signInResult, error) in …
 
**To Reproduce**
Unfortunately, this is not easy to reproduce. We were able to see the issue via logs in the app. 

**Which AWS service(s) are affected?**
AWS Cognito 

**Expected behavior**
I would expect the code to execute as expected. 

**Screenshots**

**Environment(please complete the following information):**
SDK version 2.10.3
Cocoapods
Swift 4

**Device Information (please complete the following information):**
iPhone 8 Plus
iOS 12.3.2

**Additional context**

**Comment by royjit** [comment]
Thank you for reporting this issue. Could you be able to provide more details on when this issue is happening? Is this happening when the app has been running for a while or just in the fresh install itself?
What kind of logs are you referring to?

**Comment by bfallon** [comment]
We are using cocoalumberjack for logging. It seems to happen after the app is running for a long time and the token expires. In the logs it finally started working again as expected after 7 hours.

**Comment by royjit** [comment]
Just trying to understand the behavior here. The SDK stop working for 7 hours and then it starts to work? Do you have to signIn back again to fix this?

The token expires after sometime, and the callback for service calls will wait till the token is refreshed. So the callback will wait till this happens, but this shouldnt take 7 hours. 

Also, we have made a few bug fixes related to identityId and credentials. Could you please verify that the issue is still existing - https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0.

**Comment by pedromancheno** [comment]
@bfallon Hello! Where you able to solve this issue?

**Comment by bfallon** [comment]
I believe AWS resolved the issue. I would try updating to the latest. 2.12.1
