### ISSUE TITLE
Clear authentication on re-installation / upgrade

### ISSUE THREAD

**Issue by kirilstrax** [aws-amplify/aws-sdk-ios#1930]
**State your question**
Currently, if user is signed in, and then uninstalls and then reinstalls the app (or upgrades to next version of the app), previous authentication remains valid (user is still signed in after uninstallation/reinstallation or upgrade). Is it possible to cause AWS to "forget" the user on uninstallation / reinstallation or upgrade?

**Which AWS Services are you utilizing?**
Cognito Authentication using AWS iOS SDK

**Provide code snippets (if applicable)**
To authenticate, followed demo code. Uninstallation / reinstallation is done manually (just like normal user would do it)

**Environment(please complete the following information):**
 - SDK Version: 2.11.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5
This issue was similar on previous versions

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: 12.4.1
 - Specific to simulators: no
Also reproducible on other iPhones

**Comment by palpatim** [comment]
@kirilstrax AWSMobileClient doesn't offer a feature for detecting installation/reinstallation, and it's relatively uncommon for customers to want to clear authentication during an app upgrade. You could accomplish this in your app code by keeping track of an "installation check" in the UserDefaults. Since UserDefaults are deleted when the app is deleted, that would not be present during an uninstall/reinstall scenario. Upon your app detecting that the "installation check" flag is not present, you could then do something like `AWSMobileClient.default().initialize{ _ in AWSMobileClient.default().signOut() }` to force a sign out in that case. That would cause your user to have to reauthenticate.

If you want to force reauthentication during upgrade scenarios, you could use the same process as abvove, but replacing the simple "installation check" flag with your app's version. If the current version of the app doesn't match that stored in UserDefaults, you would invoke `signOut` as shown above.

Before you do that though, I would recommend you consider the user experience of the "reauthenticate on upgrade" experience. Especially for users who have background updates turned on, such behavior would violate the expectation of seamless upgrades that users have come to expect. If you're concerned about long-lived authentication sessions, I'd recommend you explore shorter-lived refresh tokens or some other time-based mechanism.

Hope this helps.

**Comment by kirilstrax** [comment]
The authentication is clearly preserved during uninstallation and reinstallation scenario. I can reproduce it like this:
- Install application and sign in
- Uninstall application by long hold on app-> click X
- Install the app (same version) ==> still signed in
Is this unusual behavior? what could be a reason for that?
(we are not managing any authentication data outside AWS SDK)

**Comment by palpatim** [comment]
@kirilstrax Re-reading my above response, I realize I wasn't very clear in my initial explanation. Basically, what you're seeing is expected behavior based on the current design and implementation of the SDK.

Please see below for a hopefully clearer explanation, and sorry for the confusion:

---

@kirilstrax

Regarding your two cases:
1. Uninstall/reinstall: AWSMobileClient doesn't offer a feature for detecting installation/reinstallation

    To address the uninstall/reinstall case: you could accomplish this in your app code by setting an "installation check" flag in UserDefaults. Since UserDefaults are deleted when the app is deleted, that would not be present after a fresh install or uninstall/reinstall scenario. When your app detects that the "installation check" flag is not present, you could then do something like `AWSMobileClient.default().initialize{ _ in AWSMobileClient.default().signOut() }` to force a sign out in that case. That would cause your user to have to authenticate.

2. It's relatively uncommon for customers to want to clear authentication during an app upgrade

    If you want to force reauthentication during upgrade scenarios, you could use the same process as above, but replacing the simple "installation check" flag with your app's version. If the current version of the app doesn't match that stored in UserDefaults, you would invoke `signOut` as shown above.

    Before you do that though, I would recommend you consider the user experience of the "reauthenticate on upgrade" experience. Especially for users who have background updates turned on, such behavior would violate the expectation of seamless upgrades that users have come to expect. If you're concerned about long-lived authentication sessions, I'd recommend you explore shorter-lived refresh tokens or some other time-based mechanism.

Hope this helps.
