### ISSUE TITLE
Use AWSS3TransferUtility instead of deprecated AWSS3TransferManager

### ISSUE THREAD

**Issue by bzdybowicz** [aws-amplify/aws-sdk-ios#1958]
**State your question**

What is the reason of not replacing file when it exists at downloading URL? It was replacing file when downloaded using AWSS3TransferManager. Is there any other, not deprecated way to download file and replace one existing at given location?

**Which AWS Services are you utilizing?**
S3 / AWSS3TransferUtility

**Provide code snippets (if applicable)**
https://github.com/aws-amplify/aws-sdk-ios/blob/3b5f37d5008bf83b289fc6b090bbb03a27339a0f/AWSS3/AWSS3TransferUtility.m#L2523

**Comment by lawmicha** [comment]
Hi @bzdybowicz,

Thanks for the question and providing the code snippet. It looks clear from the code that when it is downloading to file (transferUtility.location is set), and file does not exist at that path, it will then place the downloaded file into transferUtility.location. I tested this in a sample app and can confirm that my file is not overridden when i download to the same location a different file from S3.

Looks like this by design, and we revisit the decision that was made and determine if we should change it to replace the file always.

Can you comment on the difficulties of having this behavior over the other? 

Is there a workaround for your use case? such as deleting the file if exists before doing the download?

**Comment by bzdybowicz** [comment]
Well, I had to obviously reimplement it myself since I need file to exist all the time, but it is pretty ridiculous to break functionality like that when updating version. I would understand if it had been new feature, but in AWSS3TransferManager it was replacing existing files...

**Comment by palpatim** [comment]
@bzdybowicz Thanks for the feedback. Although this does appear to be an intentional decision in the SDK, unfortunately none of the current team have context into why we made that decision. I agree it's unexpected to change behavior for what appears to be a drop-in replacement for an existing SDK.

Since the existing TransferUtility behavior has been there quite some time (we believe since its launch), we're not going to want to change that behavior to conform to the old TM behavior, but we'll add better documentation that explains what happens if we download to a non-empty local destination. For your case, and others who need to replace files, the workaround @lawmicha suggested is the best advice.
