### ISSUE TITLE
CognitoAuth-Sample with Google Logout doesn't work

### ISSUE THREAD

**Issue by devropes** [aws-amplify/aws-sdk-ios#1995]
Everytime I try to sign out of the sample Cognito app https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample/Swift, the app doesn't actually log out of Google. So when I try to re-login with Google, it just automatically signs in. It doesn't allow me to enter a different gmail account ever. How can this be fixed?

![image](https://user-images.githubusercontent.com/54644824/66892193-e27a1180-ef9f-11e9-9bdc-b33572e0df17.png)

**Comment by palpatim** [comment]
@devropes I verified with the Cognito Hosted UI team, and this behavior is expected, as Google (as well as other Identity Providers except for SAML) do not provide a logout endpoint for us to hit. Therefore the current behavior of the Hosted UI is the most we can currently do, as we also don’t have access to delete the Google’s cookie either. As far as we know there isn’t much you as a developer can do either, as you wouldn't have access to the Google (or any Identity Provider's) cookie. Since this is dependent on Google/any IDP providing a log-out endpoint, it’s also not a feature we can look at adding.
