### ISSUE TITLE
Pinpoint duplicates Push Notifications related events.

### ISSUE THREAD

**Issue by mureatencio** [aws-amplify/aws-sdk-ios#2042]
**Describe the bug**
Pinpoint's "interceptDidReceiveRemoteNotification" callback on swift is creating duplicate events for "_campaign.received_foreground" and "_campaign.received_background", I'm following the examples Amazon provides, but on Pinpoint campaign Metrics I'm getting duplicated events.

**To Reproduce**
A code sample or steps:
```
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        PinpointAnalyticsManager.shared.pinpoint!.notificationManager.interceptDidReceiveRemoteNotification(
            userInfo, fetchCompletionHandler: completionHandler)
        
    }
```

**Which AWS service(s) are affected?**
AWS Pinpoint iOS SDK 

**Expected behavior**
Mentioned events should only be reported once, there's no way for a push notification campaign to get delivered multiple times on the same installation instance.

**Screenshots**
<img width="1209" alt="Screen Shot 2019-11-15 at 5 46 46 PM" src="https://user-images.githubusercontent.com/2531394/68986245-d5d91b00-07e2-11ea-8a4e-936f666f8738.png">

**Environment Information (please complete the following information):**
 - AWS iOS SDK Version: 2.11.1
 - Device: iPhone 6s, iPhone 6
 - iOS Version: 12.1, 13.0
 - Specific to simulators: NO

**Comment by mureatencio** [comment]
Another example, I sent a push notification to a single user, I'm getting 3 opens count, it shouldn't be possible.

<img width="1177" alt="Screen Shot 2019-11-18 at 4 19 31 PM" src="https://user-images.githubusercontent.com/2531394/69099022-64d27700-0a1f-11ea-8fee-7d30197f5380.png">

**Comment by msteinmn** [comment]
If someone from the Amplify team could provide an answer to this, that would be great. This issue is causing production problems with an AWS Pinpoint implementation,

**Comment by lawmicha** [comment]
Hi @mureatencio, thanks for reporting the issue. From your other example, it shows "Endpoints targeted, Messages sent, Messages delivered" to be 1 so I am assuming that the pinpoint service sent this to APNS only once and that APNS only sent it to the user's endpoint only once. The pinpoint client will record the campaign event to pinpoint when the app receives the notification and it calls `notificationManager.interceptDidReceiveRemoteNotification` as you've mentioned.

I don't have exactly the issue you're seeing since I don't know enough about your code to understand why it may be recording multiple events for the same campaign_id. However, i was able to reproduce a slightly different version of it, hopefully this will provide more insight into how your app is operating.

The code in question:
```
- (void)handleNotificationReceived:(UIApplication *) app
                  withNotification:(NSDictionary *) userInfo
  shouldHandleNotificationDeepLink:(BOOL) shouldHandleNotificationDeepLink {
    UIApplicationState state = [app applicationState];
    
    if (state == UIApplicationStateInactive) {
        AWSDDLogVerbose(@"App launched from received notification.");
        [self addGlobalCampaignMetadataForNotification:userInfo];
        [self recordMessageOpenedEventForNotification:userInfo
                                       withIdentifier:nil
                                 withApplicationState:state];
        if (shouldHandleNotificationDeepLink) {
            [self handleNotificationDeepLinkForNotification:userInfo];
        }
    } else if (state == UIApplicationStateBackground) {
        AWSDDLogVerbose(@"Received notification with app on background.");
        [self addGlobalCampaignMetadataForNotification:userInfo]; // #1
        [self recordMessageReceivedEventForNotification:userInfo 
                                              eventType:AWSEventTypeReceivedBackground
                                   withApplicationState:state]; //  # 2
    } else {
        AWSDDLogVerbose(@"Received notification with app on foreground.");
        [self recordMessageReceivedEventForNotification:userInfo
                                              eventType:AWSEventTypeReceivedForeground
                                   withApplicationState:state]; // #3
    }
}
```

I moved the App to the background, and created a campaign on the pinpoint console. This sent the notification to the device and when I tapped to foreground the app, it went over 1. registered the campaign details in the global attributes for all events and 2. recorded the event with the campaign details for pinpoint service.

Then I sent the App another notification using an application that sends it directly to APNS (not using pinpoint campaigns) while it was in the foreground, it trigger number 3. to record the foreground event. Even though no campaign details were added to the event. the global attributes that were added in 2. from before were incorrectly added to this new event.

Thus for the same campaign_Id, i can see one event for `_campaign.received_foreground` and one for `campaign.received_background`.

Now, the question for the pinpoint SDK is why is it adding global campaign metadata for all notifications? To debug your issue further, can you confirm if you are recording other events in your code? If you are, I'm guessing it might be recording events with those global attributes set. If you are able to set a debugger, you'll can see that global attributes get added as part of recordEvents call in pinpoint.

**Comment by mureatencio** [comment]
Hi @lawmicha, thanks for your answer. 
Correct, we are recording many other events besides the campaign-related ones. 
I will try to set a debugger and confirm if that is the cause.

We have also noticed none of the `_campaign.received_background` events are being collected when the app is closed. Do you think this unexpected behavior could be caused by the bug you found?

**Comment by lawmicha** [comment]
> We have also noticed none of the `_campaign.received_background` events are being collected when the app is closed. Do you think this unexpected behavior could be caused by the bug you found?

From looking at the code, I believe that is expected since when the app is in the background, user presses a notification will bring the app to the foreground and send `_campaign.received_background`. When the App is terminated/closed, and the user pressing a notification will launch the app and trigger this:
https://github.com/aws-amplify/aws-sdk-ios/blob/7c6c287f5cf0313ef042d34f18b5f82b27298a30/AWSPinpoint/AWSPinpointNotificationManager.m#L90

which will send `_campaign.opened_notification`.

**Comment by lawmicha** [comment]
I updated the documentation at the bottom here in this PR regarding which events are sent and hope to iterate on it further from your pain points and feedback (https://github.com/aws-amplify/docs/pull/1104)

regarding the issue with multiple events per single campaign message. i believe this is a bug that we will have to look into further as I suspect that the global campaign attribute are added for associating a session event. The problem I see here is when i send a notification from another source other than pinpoint campaigns, they should be recognized as an notification that is not coming from pinpoint and should not record an event.

**Comment by lawmicha** [comment]
Hi @mureatencio, it has been awhile now and the bug i described, I was not able to get more than a single count for a campaign event even though code appears to be adding campaign events for non-campaign notifications. To better assess the impact of this issue, are you still seeing the issue with duplicate campaign event counts? If so, are you sending notifications to the app outside of campaigns? have you been able to verify that it is the same bug as I described above (sending non-campaign notification results in a "campaign event")
