### ISSUE TITLE
AWSS3TransferUtility never releases expression.completionHandler

### ISSUE THREAD

**Issue by jasonbobier** [aws-amplify/aws-sdk-ios#2053]
**Describe the bug**
Tasks are kept in a completed task dictionary when completed and the blocks passed into the task are never released. This causes all user objects captured to be retained.

**To Reproduce**
Upload a file for example. Pass a completion handler in that captures some objects. They will never be released.

**Expected behavior**
Completed tasks should be released at some point! Or at the very least, the passed in blocks should be released.

**Environment(please complete the following information):**
 - SDK Version: 2.12.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Comment by dydus0x14** [comment]
Hi. Any updates on this? I faced with the same issue. Seems like download/upload request has never been removed from completedTaskDictionary in AWSS3TransferUtility object. Is there any way to do that?

**Comment by jasonbobier** [comment]
I haven't heard a thing on it. I ended up setting the blocks on the task to nil in my completion block in order to prevent the retain of my objects, but that doesn't solve the original issue.

**Comment by royjit** [comment]
Looks like `completedTaskDictionary` items are not removed in the TU. We might need to remove the reference of items from the dictionary when the task get completed, `NSURLSession` delegate completion api would be the place where we need to clean up the dictionary.

**Comment by brennanMKE** [comment]
Now `AWSS3TransferUtility` includes a property named `shouldRemoveCompletedTasks` which is off by default. It can be set to `true` so that it will release all tasks once they are completed. It will also clear the expression on the task which is retaining the closures for the progress and completion handlers. The expression itself may be used for multiple operations so the handlers should not be cleared out as that would affect other operations. If you want to opt into this behavior you can set this property to `true`.

**Comment by brennanMKE** [comment]
@jasonbobier & @dydus0x14  Please let us know if this new property helps with your apps.
