### ISSUE TITLE
AWSCognitoIdentityProviderErrorDomain error 34

### ISSUE THREAD

**Issue by sungwonshin** [aws-amplify/aws-sdk-ios#2146]
**Describe the bug**
We use our own sign-in UI and pass user credentials to AWSMobileClient.sharedInstance().signIn to let users sign in.

Some of our customers are reporting the error, "The operation couldn't be completed. (com.amazonaws.AWSCognitoIdentityProviderErrorDomain error 34.)" during sign-in. The customers are in our user pool and their accounts are confirmed.

The error is AWSCognitoIdentityProviderErrorUserNotFound. I expected AWSMobileClient.sharedInstance().signIn returns AWSMobileClientError.userNotFound, but it was not for this error.

So, when does the signIn API return AWSCognitoIdentityProviderErrorUserNotFound directly from Cognito instead of AWSMobileClientError.userNotFound?  This problem occurs only in our iOS app and the user's can sign in thru our web app fine.

**To Reproduce**
Some of our customers reported this error, but we couldn't reproduce the bug internally.  We did try to sign in using the customer's credentials (with their permission) and we could not reproduce the error.

**Which AWS service(s) are affected?**
Amplify/Cognito

**Expected behavior**
No sign-in error for a confirmed user in the user pool.

**Environment(please complete the following information):**
DM: Cocoapods
AWSCore: 2.9.1
AWSCognitoIdentityProvider: 2.9.1
Swift: 5.0

**Device Information (please complete the following information):**
iOS: 13.x

**Comment by palpatim** [comment]
You may be encountering an issue with casting errors that was fixed in [2.9.4](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.9.4)

>   * Fixed issue where error was not correctly cast to `AWSMobileClientError` when using `changePassword` API. [issue #1246](https://github.com/aws-amplify/aws-sdk-ios/issues/1246)

Does this issue still occur on the [latest release](https://github.com/aws-amplify/aws-sdk-ios/releases)?

**Comment by sungwonshin** [comment]
@palpatim I have updated my app with the latest AWS sdk and will deploy the app next time.  But, what would you recommend to diagnose the user not found error for the user with a confirmed Cognito account in our user pool?  This was the problem I was trying to report.  Thanks.

**Comment by palpatim** [comment]
https://github.com/aws-amplify/aws-sdk-ios/issues/1495 reports logged-in users being evaluated as "not found" in certain cases where the User Pool is configured to allow users to sign in via username or email. It may be that your users are being caught by this if they're signing in with an unverified email.

Beyond that, the only troubleshooting we could do is to increase the log level and inspect logs coming back from the service during a "UserNotFound" condition, which might help us understand which flow is triggering the response.

**Comment by sungwonshin** [comment]
@palpatim When I took a look at the user's account who has the sign-in problem, his email was verified and the account was enabled and confirmed.  I'm not sure why Cognito returned the "user not found error" though.

**Comment by kneekey23** [comment]
@sungwonshin was your issue fixed with the update?

**Comment by sungwonshin** [comment]
Yes.  We haven't seen any login issue reports from our customers, so the updated SDK seems to fix the problem.

**Comment by kmoore812** [comment]
I am experiencing this issue, and I have updated SDK 

Can not retrieve location : error APIError: Failed to retrieve Cognito UserPool token.
Caused by:
AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/kxxxxx/Development/xxxxxx/IOS/myredactedappname/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=34 "(null)" UserInfo={__type=UserNotFoundException, message=User does not exist.}

**Comment by lzaprivoda** [comment]
Same Error (though it doesn't happen often and very hard to reproduce):
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=34

**Comment by sungwonshinn** [comment]
For those experiencing the error code 34 (AWSMobileClientError.userNoFound,)  the error occurs when:

1. A user is signed in once. AWSMobileClient will cache the refresh token in the keychain.
2. The user's account in the user pool gets deleted. The cached refresh token in the keychain is now invalid because the account is deleted, but AWSMobileClient.initialize and isSignedIn will still return true because it only checks the existence of the token (expected behavior.)
3. AWSMobileClient.getTokens will validate the cached refresh token and it will fail with the error code 34 because the refresh token is no longer valid (no user account.) In this case, the user-state-changed callback is not called. Also, AWSMobileClient.signOut must be called before signIn method with new credentials is invoked, otherwise you will get AWSMobileClientError.invalidState error.
