### ISSUE TITLE
How to integrate sdk for project that does not use Cocoapod?

### ISSUE THREAD

**Issue by apanagar** [aws-amplify/aws-sdk-ios#22]
My project doesn't use Cocoapod. Is there a way I can easily include the source? Cocoapods is not an option for me, and in my development environment I would rather include source than just link against the static library.

**Comment by Motti-Shneor** [comment]
I am in similar situation - I can't use cocoaPods for several technical reasons - besides I really dislike this system as it overruns Xcode native build configurations, and denies lots of flexibility in Apple's build system. 

Now I can have AWS repository as my git submodule - but your Xcode project does NOT have any static-lib targets. only frameworks. and since my own project produces an sdk (in the form of a framework) and I do not wish my clients to need to struggle with umbrella frameworks (carrying AWS frameworks within my own framework) I really need to build aws-sdk-ios as static lib. Why isn't this supported in your Xcode project?

**Comment by ppamorim** [comment]
@Motti-Shneor By running this script below you are able to compile the frameworks:

```shell
AWS_SCHEMES="AWSCore AWSS3 AWSLogs"
for SCHEME in ${AWS_SCHEMES}; do
  sh CircleciScripts/package_sdk.sh ${SCHEME}
done
```

**Comment by Motti-Shneor** [comment]
I already managed to make AWS SDK part of my code-base using git submodules, which I find many times better than CocoaPods.

I tried to use AWS SDK Xcode build targets, but shamefully they didn’t even build… 

So I created my own targets for AWS’s 3 libraries I needed, added them as dependencies to my iOS App target, and linked against them,

And that’s all. 

I now have the AWS (rather cumbersome and mostly unusable) SDK build and optimize directly Into my own SDK, without dynamically linking, umbrella framework, or the atrocities of CocoaPods generated targets.

Thanks anyway.

BTW - building via scripts usually cripples Xcode build system very much.
Clean target will break (won’t clean whatever is build by the script)
Change in one of the sources built by the script - won’t trigger a build, so you will need to remember that and manually clean before build (see #1)
There will not be compiler+linker level integration between the AWS SDK and my own code (optimizations, compiler flags, linker flags, etc.)

So… thanks! But no-thanks. 


Motti Shneor, 
CEO,  Tchelet Technologies LTD.
Software Development for Apple Platforms

Address: 34 Emek-Ha-Ella St. Appt.1 Modiin, ISRAEL, 7173147
Tel/Fax: +972-8-9267730
eMail: motti.shneor@gmail.com 
Mobile phone: +972-54-3136621
---
ceterum censeo microsoftiem delendam esse
---
