### ISSUE TITLE
How to get url of image after I upload it to S3?

### ISSUE THREAD

**Issue by student-101** [aws-amplify/aws-sdk-ios#2214]
I want to get url after I upload a file.
How could I implement？

**Comment by royjit** [comment]
Hi @student-101 

You should be able to get the url using presigned url builder in S3 SDK. More information can be found [here](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSS3/Classes/AWSS3PreSignedURLBuilder.html).

**Comment by student-101** [comment]
```
let url = AWSS3.default().configuration.endpoint.url
let publicURL = url?.appendingPathComponent(bucketName).appendingPathComponent(uploadKeyName)
```
This worked perfectly.

**Comment by royjit** [comment]
@student-101 

It worked because your s3 object has public ready property. It is not a best practice to give your s3 objects public access. Please follow the recommended best practices - https://docs.aws.amazon.com/AmazonS3/latest/dev/security-best-practices.html
Amplify iOS docs - https://aws-amplify.github.io/docs/sdk/ios/storage
