### ISSUE TITLE
FORCE_CHANGE_PASSWORD Users don't get emails verified

### ISSUE THREAD

**Issue by dconroy** [aws-amplify/aws-sdk-ios#2221]
**Describe the bug**
New users created with the Cognito management console will not get their email addresses verified after a successful login with a temporary password. This will make it impossible for them to use forget password functionality in the future.

This issue surfaced when I was migrating my app from one aws org to another, and needed to create a new user pool. I would like to prepopulate my new user pool with my existing users/email addresses, prompting them with a temp password. However, after they successfully login and set a new password - they do not get their email address verified.

Image link: https://imgur.com/ouu8GCW

If i prepopulate them selecting verified email address - they get the issue here:
https://github.com/aws-amplify/aws-sdk-ios/issues/2203
"Cannot modify the non-mutable attribute email_verified"

Create a new user in cognito user pool without a verified email address. Attempt login through aws ios sdk with temporary password. Verify in user pool that email address is not verified.

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
After a user logins with a temporary password from their email, their email address should be confirmed in cognito.

**Screenshots**
Image link: https://imgur.com/ouu8GCW

**Environment(please complete the following information):**
PODS:
  - Alamofire (4.9.1)
  - AppleWelcomeScreen (1.0.2):
    - SnapKit
  - AWSAuthCore (2.12.5):
    - AWSCore (= 2.12.5)
  - AWSAuthUI (2.12.5):
    - AWSAuthCore (= 2.12.5)
    - AWSCore (= 2.12.5)
  - AWSCognitoIdentityProvider (2.12.5):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.12.5)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.12.5)
  - AWSMobileClient (2.12.5):
    - AWSAuthCore (= 2.12.5)
    - AWSCognitoIdentityProvider (= 2.12.5)
  - AWSS3 (2.12.5):
    - AWSCore (= 2.12.5)
  - AWSUserPoolsSignIn (2.12.5):
    - AWSAuthCore (= 2.12.5)
    - AWSCognitoIdentityProvider (= 2.12.5)
  - Cache (5.2.0)
  - ESTabBarController-swift (2.7)
  - Imaginary (4.2.0):
    - Cache (~> 5.0)
  - Kingfisher (5.12.0):
    - Kingfisher/Core (= 5.12.0)
  - Kingfisher/Core (5.12.0)
  - Lightbox (2.3.0):
    - Imaginary (~> 4.0)
  - lottie-ios (3.1.5)
  - Mapbox-iOS-SDK (5.6.1):
    - MapboxMobileEvents (= 0.10.2)
  - MapboxMobileEvents (0.10.2)
  - Realm (4.3.0):
    - Realm/Headers (= 4.3.0)
  - Realm/Headers (4.3.0)
  - RealmSwift (4.3.0):
    - Realm (= 4.3.0)
  - SnapKit (5.0.1)
  - WSTagsField (5.2.0)
 - Dependency Manager: Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
N/A

**Additional context**
Issue arising due to need to migrate user pools from one aws org to another.

**Comment by lawmicha** [comment]
Thanks for the detailed information. For the migration scneario, my thought is that a user’s email verification status should be the same in the new user pool, ie. migrate a user with email_verified whether it’s true or false over to the new user pool with the same value.

**If user’s email is verified in old user pool**

1. Create a new user in the user pool (email is verified, send temp password to their email, FORCE_CHANGE_PASSWORD state)
2. User logins using temporary password and gets a response back from Cognito containing “email_verified = true”. 
3. App asks user to provide new password. Sends new password to Cognito should be successfully after workaround is in place (https://github.com/aws-amplify/aws-sdk-ios/issues/2203). the user will then be Confirmed with a verified email.

The experience for the end user is that they will have to enter the temporary password after the migration, and choose a new password.


**If user’s email is not verified in old user pool**

1. User is created in old user pool. Code is sent to email.
2. User never enters the code received in the email to confirm sign up. email is not verified.

1. Create a new user in the user pool (email is not verified, FORCE_CHANGE_PASSWORD)
2. Sign in with temporary password. Ideally, since email is not verified, the user that enters the new password should move the user to “Unconfirmed” and then a code should be sent to their email, and confirming the code should then move the user to Confirmed. Because FORCE_CHANGE_PASSWORD goes to CONFIRMED, I suspect that this flow (FORCE_CHANGE_PASSWORD -> UNCONFIRMED -> CONFIRMED) is not supported. 

The question would narrow down to, how do we verify the email of a user that is CONFIRMED?

**Comment by lawmicha** [comment]
There should be a way to check to see if email is not verified, then show an action to get a code sent to that email, then allow the end user to enter it to confirm their email attribute.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUserAttributeVerificationCode.html
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_VerifyUserAttribute.html

Checking to see if this is supported AWSMobileClient

**Comment by lawmicha** [comment]
I will have to confirm this but https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html should be able to get `email_verified` attribute and check that the value is false.

the app code can check for this and act accordingly (ie. prompt user to verify email, send code, verify code) after the user has logged in.

**Comment by lawmicha** [comment]
> I will have to confirm this but https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html should be able to get `email_verified` attribute and check that the value is false.
> 
> the app code can check for this and act accordingly (ie. prompt user to verify email, send code, verify code) after the user has logged in.

So the behavior I see is that when a user is created on behalf of the end customer, in my case, I created a new user in AWS Console on the Cognito User Pool page with "email verified" unchecked.  The user is created with "FORCE_CHANGE_PASSWORD" state. I go back to the app and enter the temporary password, and then enter a new password. the user is now in CONFIRMED state. the "email_verified" attribute is empty so when I call get user attributes, the attribute is never returned. In the Cognito Console, there's is a dash for the value of "email_verified" attribute, and so it is not "false" but the attribute value does not exist. I believe the app code would then need to check that there is no user attribute "email_verified" when calling getUserAttributes, if the key does not exist then it also implies that it is not verified. Then you can continue to prompt the user to `verifyUserAttribute(attributeName: "email")` and `confirmVerifyUserAttribute(attributeName: "email"`
