### ISSUE TITLE
Crash when stripping invalid identity user pool id

### ISSUE THREAD

**Issue by stevenkramer** [aws-amplify/aws-sdk-ios#2272]
**Describe the bug**
It's possible to feed an invalid pool id into the configuration. The id is later assumed to match a certain format. The assumption causes a crash here:

- (NSString*) strippedPoolId {
    return [self.userPoolConfiguration.poolId substringFromIndex:[self.userPoolConfiguration.poolId rangeOfString:@"_" ].location+1]; // <<<< location will be NSNotFound i.e. a very large number
}

**To Reproduce**

            let poolConfiguration = AWSCognitoIdentityUserPoolConfiguration(
                clientId: identityPoolClientId, // <--- I used the identity pool here: "eu-west-2:def279a2-b4a1-4dd8-8138-dc1ca22525bf"
                clientSecret: identityPoolClientSecret,
                poolId: identityPoolId)

Attempt to log in using this pool, it will crash at some point.

**Which AWS service(s) are affected?**

Cognito.

**Expected behavior**
No crash / prevalidation of the pool id.

**Screenshots**

**Environment(please complete the following information):**
Carthage, Xcode 11.3, 7865fe4b448ea7d2a5425b9ab027ace544217b00 

**Device Information (please complete the following information):**
Simulator 11.3

**Additional context**

**Comment by drochetti** [comment]
Thanks for reporting this. In fact we don't pre-validate configuration values format.

Can you walk me through how you came across this? It would be useful to understand all the scenarios where the `poolId` would be invalid.

**Comment by stevenkramer** [comment]
Well, manual configuration, so I was to blame… But not validating the assumptions before running code that depends on them should be fixed.

I'm pretty sure I did get validation failures on other configuration values though.

**Comment by palpatim** [comment]
@stevenkramer Thanks for the report, but I don't think we're going to try and pre-validate this input in the current code. There might be good places to do this during configuration and initialization, but by the time we get down to the `strippedPoolId` method, there's no way to recover gracefully from a malformed ID. Given that this results from manual configuration, as opposed to the recommended path of using Amplify CLI to configure, we feel we have better ways to fix this by examining the overall configuration scheme rather than targeting this one point of pain.
