### ISSUE TITLE
(401 unauthorized) Did not receive a successful HTTP code

### ISSUE THREAD

**Issue by mohaumpoti** [aws-amplify/aws-sdk-ios#2275]
**State your question**
Please help me figure out what causes the 401 unauthorized error. The error appears intermittently during a create mutation transaction. That is to say, most times the transaction succeeds, but in some instances, the 401 error appears.

**Which AWS Services are you utilizing?**
AppSync, GraphQL, Authentication with Cognito User Pools

**Provide code snippets (if applicable)**

`     
        
        // Reference AppSync client from App Delegate
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        appDelegate.appSyncClient?.perform(mutation: CreateFoodLogMutation(input: CreateFoodLogInput(mealType: mealType.rawValue, timestamp: Date().iso8601String)), resultHandler: { (result, error) in
            if let error = error {
                completion(.failure(error))
                return
            } else if let result = result, let createFoodLog = result.data?.createFoodLog {
                // Convert the timestamp (String) to Date
                let dateFormatter = DateFormatter()
                dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"
                let timestampDate = dateFormatter.date(from: createFoodLog.timestamp)
                
                let foodLog = FoodLog(id: createFoodLog.id, mealType: createFoodLog.mealType, timestamp: timestampDate!)
                completion(.success(foodLog))

                return
            }
                    
        })`

**Environment(please complete the following information):**
 - AppSync SDK: 3.0.0
 - AppSync Auth Types: Primary = Cognito User Pools, Secondary = IAM
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone10
 - iOS Version: iOS 13

**Comment by palpatim** [comment]
@mohaumpoti How are you handling authentication in your app? If you're using AWSMobileClient, please remember that its initialization is asynchronous, and you need to ensure it's initialized before making authenticated calls. Similarly, be sure to register a listener for user state changes, so you can respond appropriately when the User Pools refresh tokens expire. More info here: https://aws-amplify.github.io/docs/ios/authentication

If you're using Cognito User Pools directly, rather than via AWSMobileClient, how are you managing credential refreshes? The intermittent behavior you describe is symptomatic of an expired access token. AWSMobileClient manages this on your behalf, but if you're using the UserPools client instead, you'll have to do those refreshes yourself.

**Comment by mohaumpoti** [comment]
Hey @palpatim! Thanks for your response. I use AWSMobileClient to handle authentication, and I found out that the tokens were getting expired (hence the 401 unauthorized error on the api). I was able to resolve this by doing 2 things:

- In the IAM console, I changed the session duration of the authenticated role from the default 1 hour to 12 hours.
- On the client side, I now obtain refreshed tokens after the session duration has expired, which I use to re-initialize AppSync with.

That seems to have solved the problem.
