### ISSUE TITLE
Pinpoint error writing to sqlite in background

### ISSUE THREAD

**Issue by Dachmian** [aws-amplify/aws-sdk-ios#2276]
**Describe the bug**

When entering background on rare occasions I get many error messages from AWS pinpoint that is trying to write some logs to sqlite.

**To Reproduce**
1. Start application
2. wait for it to initialise
3. Put app in background and lock device
4. See error messages get printed out

**Which AWS service(s) are affected?**
AWS Pinpoint

**Expected behavior**
No errors from writing to sqlite

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.12.6
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone Xr
 - iOS Version: iOS 13+
 - Specific to simulators: No
[pinpoint.log](https://github.com/aws-amplify/aws-sdk-ios/files/4166337/pinpoint.log)

**Additional context**

**Comment by palpatim** [comment]
@Dachmian 

The behavior you're describing sounds a lot like an error due to [Data Protection](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files)

I'm having trouble figuring out the conditions that would cause this though. By default, iOS' Data Protection is enabled at `CompleteUntilFirstUserAuthentication` -- that is, access is blocked until the phone is unlocked for the first time. If your repro steps are accurate (that is, it happens immediately upon locking the device, rather than seeing the error after a device reboot when the app is woken up for, say, a push notification or background url task), then your app may be protected with a [Data Protection entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_default-data-protection) that declares a higher level than default. In that case, we would have to take a feature request to allow Pinpoint's Database to be created with a custom protection level. 

Side note: I haven't tested whether file protection settings are inherited by objects within a directory--that is, if you create a directory with custom file protection, are objects within it created with the default specified by your entitlements, or with the overridden protection specified at directory creation time? If the latter, then you could potentially work around this by pre-creating the Pinpoint database directory at app launch, with a lower data protection level such as `CompleteUntilFirstUserAuthentication`. You can see this code for how Pinpoint derives its path: temporaryDirectory + AWSPinpointClientRecorderDatabasePathPrefix:

https://github.com/aws-amplify/aws-sdk-ios/blob/f84cab034ebb5e67a13e0d3d40c6238dd7ec3289/AWSPinpoint/AWSPinpointEventRecorder.m#L97

**Comment by Dachmian** [comment]
@palpatim 

Thank you for the reply. Data Protection is not enabled right now, but this was enabled in my app some time ago and I guess the issue relates to that.

I will pre-create the Pinpoint data base directory and try to see if the error shows itself again.

I will close and reopen if needed.

Thank you.
