### ISSUE TITLE
How can I use SDWebImage with S3?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/aws-sdk-ios#2282]
Hello,

I would like to know your opinion about this.

In my app, users upload pictures and see others users pictures (like a social network).
I guess I have to use the "protected" permission.

Because I use Aurora Serverless, I cannot use S3ObjectInput. I think that feature is called "GraphQL APIs (Complex Objects)". 
But it seems to me it is not a problem.

Anyway, my idea is to upload pictures from the iPhone app using:
```
let transferUtility = AWSS3TransferUtility.default()
transferUtility.uploadData(data, bucket: "YourBucket", key: "YourFileName",....
```
Where "YourBucket" is protected/\(cognitoIdentityId)/, right? and for key, I could use a UUID with JPG as extension.

After uploading the picture, I could save that key into my Aurora database, just another field for that user (or another table, it does not matter now).

My question is, how to download that picture properly when other users are visiting that user profile?

If I want to use SDWebImage, or similar library, I need a URL, not a key.

Do I have to calculate a  Pre-signed URL every time I visit a profile from keys saved in that profile? I mean, when I download a user's profile using GraphQL/Aurora, I have a list of keys (the pictures), but for SDWebImage I need URLs.
Should I use `AWSS3PreSignedURLBuilder.default().getPreSignedURL` all the time?
Is it asynchronous or synchronous operation?
Should I use `Amplify.Storage.getURL(key: "myKey")` ?
What about using `getPreSignedURLRequest.expires` with a lot of years and then I save that URL into the database? Is this crappy solution?

Note that all these picture can be accessed by everyone, permissions is not a problem.

Thanks for all your suggestions.

**Which Category is your question related to?**
Storage

**Amplify CLI Version** 
4.13.2

**What AWS Services are you utilizing?**
S3, Cognito, Aurora, AppSync

**Comment by palpatim** [comment]
> I guess I have to use the "protected" permission.

That would be most appropriate for your case, yes.

> Where "YourBucket" is protected/(cognitoIdentityId)/, right? and for key, I could use a UUID with JPG as extension.

`YourBucket` is your S3 bucket name. The `protected/(cognitoIdentityId)/` string would be prepended to your object's key, as in 

```swift
let transferUtility = AWSS3TransferUtility.default()
let key = "protected/\(cognitoIdentityId)/\(UUID().uuidstring)"
transferUtility.uploadData(data, bucket: "YourBucket", key: key,....
```

> Should I use `AWSS3PreSignedURLBuilder.default().getPreSignedURL` all the time?

Yes, that is the intent of the URL builder, to provide URL-based access to objects for a set period of time. You can define your expiration policy (up to S3's maximum of 7 days). SDWebImage should cache the image locally so your image will only request from the server on a cache miss. If you detect a cache miss, you can generate a new presigned URL and re-submit that as your SDWebImage source URL.

> Is it asynchronous or synchronous operation?

Because it relies on your current user's credentials to generate a presigned URL, `getPresignedURL` is an asynchronous operation.


> Should I use `Amplify.Storage.getURL(key: "myKey")` ?

All of the above discussion is for the "legacy" SDK. Bear in mind that Amplify is still in preview, but we're working hard to get it to general availability. 

If your use case supports using a preview library, you can certainly use `Amplify.Storage.getURL()`. That API doesn't require you to prepend "protected/\(cognitoIdentityId)/" to your key--instead you pass the access level and Amplify calculates the correct key for you:

```swift
Amplify.Storage.getURL(key: "myKey") { (event) in
    switch event {
    case .completed(let data):
        print("Completed: \(data)")
    case .failed(let storageError):
        print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    default:
        break
    }
}
```

> What about using `getPreSignedURLRequest.expires` with a lot of years and then I save that URL into the database? Is this crappy solution?

No, the maximum expiry of a presigned URL is 7 days (604800 seconds). The use case for PresignedURLs is to temporary access to resource. We're exploring other ways of solving your use case and will update when we have more information.

In the meantime, I'm going to leave this open as a Feature Request so we don't lose track of this.

**Comment by Ricardo1980** [comment]
Thanks a lot @palpatim for your clarification!

> Because it relies on your current user's credentials to generate a presigned URL, getPresignedURL is an asynchronous operation.

Let me clarify my question, I wanted to say if getPreSignedURL sends a network request (or can take several seconds).

> Yes, that is the intent of the URL builder, to provide URL-based access to objects for a set period of time. You can define your expiration policy (up to S3's maximum of 7 days). SDWebImage should cache the image locally so your image will only request from the server on a cache miss. If you detect a cache miss, you can generate a new presigned URL and re-submit that as your SDWebImage source URL.

Let's forget about caching for a while.
Imagine I open the profile screen, using GraphQL/AppSync/Aurora I download info about that profile every time you open the profile screen. Some of the info is the name (keys) of 6 images. Does this mean that now I have to call getPreSignedURL six times (once per image) and then send those 6 URLs to SDWebImage?

Apart from this, when caching is involved, I guess I could avoid that step as you already commented.
My idea is that users can create or delete images, but not modify them. So, because I use UUIDs (which means, never repeated), I can implement a very aggressive caching policy. Basically, If the name is in the cache, use it, always. What do you think?

Do you see any problem when working with tables that can present 10 or 20 cells at the same time? each one with one image (a thumbnail).
This means that potentially, I could call getPreSignedURLabout 10 or 20 times at the same time, and if you scroll, more times. Is that OK?

> All of the above discussion is for the "legacy" SDK. Bear in mind that Amplify is still in preview, but we're working hard to get it to general availability.

Awesome! Do you know more or less how long we have to wait? Months?

**Comment by palpatim** [comment]
> Let me clarify my question, I wanted to say if getPreSignedURL sends a network request (or can take several seconds).

Yes, if the credentials need to be refreshed, then the `getPresignedURL` operation will block until the new credentials are retrieved from the network. The actual calculation of a presigned URL, once credentials are retrieved, doesn't make any network calls, which means you would be safe to call that in a table-load situation such as you describe.

One thing we've suggested in the past is to pre-warm the cached credentials by issuing a `credentials` call (eg., `AWSMobileClient.default().credentials { print("Credentials refreshed") }`) prior to the operation that requires you to create a bunch of presigned URLs. That way the credentials are up to date and won't incur network traffic on the initial calls. There are also conditions where long-running "get credentials" operations can cause a batch of "get presigned URL" operations to fail because they exceed the 5 second timeout, so if your use case is to create several URLs at once, pre-warming the credentials is a good idea.

> Awesome! Do you know more or less how long we have to wait? Months?

We're working hard on getting it ready for GA, but don't have an ETA just yet. We'll definitely be announcing it loudly when we're ready though--we're super excited about Amplify iOS and want to get this into production!

> Last question, is there any mechanism to upload several files at the same time? in the same network request.

There is no mechanism to upload several files in a single request--I'm not even sure what you mean by that unless you're talking about using HTTP/2 to multiplex connections or something. TransferUtility does send requests concurrently though, so if you add 10 files to the upload queue, TU would send several of them at once, which means your upload should go faster than sending them one at a time.

Hope this helps.

**Comment by Ricardo1980** [comment]
Hello @palpatim 

Can you tell me your opinion about this?

I am using "protected" level in my case, but apart from that, I would like anyone in the world can read the files (but not list them) using a URL, like a static web site. That's because I will send emails with pictures that are in this bucket and other similar use cases.

I guess I have to modify manually the "s3-cloudformation-template.json" file and add "PublicAccessBlockConfiguration" like:

```
	"Resources": {
		"S3Bucket": {
			"Type": "AWS::S3::Bucket",
			"PublicAccessBlockConfiguration": {
  				"BlockPublicAcls" : false,
  				"BlockPublicPolicy" : false,
  				"IgnorePublicAcls" : false,
  				"RestrictPublicBuckets" : false
			}
			... other generated keys
		}
	}
```

Apart from that, should I modify "parameters.json" and then change: "GuestAllowList": "ALLOW" and "AuthenticatedAllowList": "ALLOW" to "DISALLOW"? (Because I don't want that anyone lists anything)

In the cloud formation template, inside the "S3Bucket" key, I see about how the resource is created, its name, and something like CORS, but I don't see how the permissions and setup for this resource. How is the link done between the resource and access permissions? I cannot see it. 

Another question, when using "amplify storage add", what is the difference between "authenticated users" and "guest users"? Is authenticated users the current user and guest users the other authenticated users?

Thanks a lot for your time.

**Comment by palpatim** [comment]
@Ricardo1980 

Sorry for the late reply on this.

> Another question, when using "amplify storage add", what is the difference between "authenticated users" and "guest users"? Is authenticated users the current user and guest users the other authenticated users?

A "guest user" is a user of your app who has not yet signed in. An "authenticated user" is a user of your app who has signed in. When thinking about this in terms of storage access levels, it's an important distinction that "readable by a guest user" *is not the same as* "world readable". So for example, if you upload an image to S3 with `public` access level, that means "any authenticated or unauthenticated user of my app can read this image", but does *not* mean, "anybody on the internet can read my image." Which is why your first question is relevant and important: It's reasonable to think that you might want to support say, a profile picture that is owned by the user and uploaded by your app, but world-readable for some random internet user browsing your site in Safari.

I need to find our recommendation for best practices for world-readable assets, since there are a couple of options for this, with different implications for cost, ease-of-maintenance, and security. I'll reply here when I have done that research.

**Comment by Ricardo1980** [comment]
@palpatim Thanks a lot for clarification.

I just need world access for my emails. Cloudfront is not needed at the moment.

I modified manually my bucket cloud formation template so it is open to the world, and it is working.
It would be nice you add this user case in the future: World wide access.

**Comment by palpatim** [comment]
Thanks for the update. Since we're tracking the feature on the [CLI feature request](https://github.com/aws-amplify/amplify-cli/issues/1910) mentioned above, I'm going to close this one to keep conversation in one place.
