### ISSUE TITLE
No way to reset an ongoing custom authentication flow

### ISSUE THREAD

**Issue by hossamghareeb** [aws-amplify/aws-sdk-ios#2300]
**Describe the bug**

There is no way to reset or cancel the current custom auth flow before initializing new one again.

**To Reproduce**
1. Start a custom auth flow by calling `awsClient.signIn(username: email, password: "dummyPassword")`
2. Then if `result.signInState == .customChallenge` we start the cycle challenge and answer by calling `awsClient.confirmSignIn(challengeResponse: answer)`
3. If the lambda function is expecting an Answer and we repeat step #1 again, we will get an error saying `invalidParameter`

**Which AWS service(s) are affected?**

**Expected behavior**

An API to reset the current session and be able to sign in without getting an error.

**Environment(please complete the following information):**
 - SDK Version: 2.12.6
 - Dependency Manager: Cocoapods

**Additional context**

I did some debugging and the problem is that `self.userpoolOpsHelper.customAuthChallengeTaskCompletionSource` is not nil in `AWSMobileClientExtensions.swift` and there is no API to reset it

**Comment by wooj2** [comment]
Hi @hossamghareeb ,

Thanks for reporting this.  This looks to be fixed in our latest version 2.12.7 w/ the following PR:
https://github.com/aws-amplify/aws-sdk-ios/pull/2265/files

Seems like all you would need to do is 
1. upgrade to the latest version 2.12.7
2.  Call signOut() to clear out `customAuthChallengeTaskCompletionSource`

I am optimistically closing this ticket, but if problems persist, feel free to re-open this ticket.  Thanks again!
