### ISSUE TITLE
AWSUICKeyChainStore crash (rejected by Apple)

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/aws-sdk-ios#2302]
**Describe the bug**
Our app was rejected by Apple because of a crash in the AWSUICKeyChainStore class.

**To Reproduce**
I cannot reproduce, but the reviewer at Apple states that it crashes on app start. 

**Which AWS service(s) are affected?**
Class: AWSUICKeyChainStore 
line 457:     `OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, &data);`

**Expected behavior**
App launches without crashing

**Environment(please complete the following information):**
 - SDK Version: 2.12.1
 - Dependency Manager: Cocoapods
 - Swift Version : 4

**Device Information (please complete the following information):**
 - Device: Unknown
 - iOS Version: 13.3.1
 - Specific to simulators:

**Comment by wooj2** [comment]
@bfallon-
Thanks for reaching out to us, and sorry to hear your app was rejected by Apple.  Based on the issue you are describing, it sounds very similar to this bug filed here (but still unclear whether or not it is the same):
https://github.com/aws-amplify/aws-sdk-ios/issues/1217

Issue 1217 does describe a workaround, which was +1'ed by another member.  But, of course it would be better to just fix the issue in the SDK.  Based on the lack of status info on the issue, I can only guess that we had problems reproducing the error and coming up with a solid fix.

Is there any chance you can share additional details about how you are using the AWS SDK?  Since the crash is being reported to happen during app start-up, can you share some of the calls you are making during the app starting up/initialization?  Is there any chance you have a stack trace?  Preferably, I'd be able to reproduce exactly the issue you're seeing, correlate it to any existing bugs, and come up with an accurate fix.

**Comment by royjit** [comment]
Another possible related issue - [#2054](https://github.com/aws-amplify/aws-sdk-ios/issues/2054)

**Comment by kneekey23** [comment]
hi @bfallon im looking into this issue. I tried reproducing based off of #2054 but wasn't able to. Can you send me exact steps to reproduce or more info on when the crash happens? Thanks!

**Comment by kneekey23** [comment]
@bfallon and 	karasahinemre have you guys tried enabling keychain sharing in your apps per #463
