### ISSUE TITLE
iOS 13.3.1 dyld: Library not loaded

### ISSUE THREAD

**Issue by litengwork** [aws-amplify/aws-sdk-ios#2316]
dyld: Library not loaded: @rpath/AWSAPIGateway.framework/AWSAPIGateway
 Referenced from: /private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Sample
 Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway: code signature invalid for '/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway'
/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway: code signature invalid for '/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway'
/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway: stat() failed with errno=1
/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway: code signature invalid for '/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway'
/private/var/containers/Bundle/Application/B38AB013-6999-4B45-981B-59605688BB7C/Sample.app/Frameworks/AWSAPIGateway.framework/AWSAPIGateway: stat() failed with errno=1
(lldb)

**Comment by royjit** [comment]
Hi,
Can you please explain the issue here?  Please provide the following details:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Which AWS service(s) are affected?**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here.

**Comment by litengwork** [comment]
Because the pod 'AWSAPIGateway', '~> 2.8.4' imported using Cocoapods, the project cannot be compiled successfully.
[AWSAPIGateway]
 - SDK Version: [2.8.4]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5]
 - Device: [iPhone11]
 - iOS Version: [iOS 13.3.1]

**Comment by royjit** [comment]
The version that you are using is pretty old. Could you please try with version `2.12.7`
