### ISSUE TITLE
CRASH: nsinternalinconsistency cannot set result of completed task

### ISSUE THREAD

**Issue by mauclores** [aws-amplify/aws-sdk-ios#2374]
**Describe the bug**
Crash happens when a user with a status FORCE_CHANGE_PASSWORD attempts to change password to an invalid password first, then a valid password next.
It appears the AWS Completion Task result is set twice, which crashes the app.

**To Reproduce**
1. Create a user with status FORCE_CHANGE_PASSWORD
2. Attempt to change password to invalid one
3. Attempt to change password to valid one
4. App crash

**Which AWS service(s) are affected?**
1. AWSCognitoIdentityProvider

**Expected behavior**
No crash

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 7
 - iOS Version: 13

**Comment by wooj2** [comment]
Hi @mauclores,

Thanks so much for reaching out to us.  Just curious: is there was a specific reason as to why you have chosen to adopt AWSCognitoIdentityProvider?  It is a dated, low level library that we no longer recommend users adopt to handle authentication.

Instead of AWSCognitoIdentityProvider, we recommend customers adopt the AWSMobileClient as it providers higher level APIs to interact with Auth.  Information can be found about the AWSMobileClient here:
https://aws-amplify.github.io/docs/ios/authentication

**Comment by mauclores** [comment]
Since it is a legacy code and started to use AWSCognitoIdentityProvider, switching to a different library at this point is difficult.

But we will look into AWSMobileClient as suggested. Thank you.
