### ISSUE TITLE
Sign up using hotmail couldn't receive verify code

### ISSUE THREAD

**Issue by morris-lu** [aws-amplify/aws-sdk-ios#2383]
Hi, I've setup Userpool sign up with email attribute and it works well. Just notice when the user signs up using Hotmail account couldn't receive verify code, even set up the sender is safe in Hotmail setting still not receive. 

Is any setting can fix this issue? Thank you very much.

**Environment(please complete the following information):**
 - SDK Version: AWSMobileClient 2.12.1
 - Dependency Manager:  Cocoapods 
 - Swift Version :  5.0

**Device Information (please complete the following information):**
 - Device: iPhone X
 - iOS Version: iOS 13.3

**Comment by wooj2** [comment]
Hi @morris-lu 

Thanks for reaching out, and sorry to hear that you're having issues receiving verify code emails.

1.  What email are you setting up as the "safe sender"?
2.  Can you think of any other options that are in hotmail that might be blocking these e-mails?
3.  Can you please provide the domain of the email address?  Is it just <someUser>@hotmail.com or some other domain?
4.  Are there any other settings that are unique to this account?

In the mean time, this does not seem to be a bug that is specific to the AWS iOS SDK, so I will open an internal ticket with the cognito team to see if they are aware of any specific settings that might stop confirmation emails going to hotmail.

**Comment by wooj2** [comment]
Hi Morris-lu

I just tried to create a hotmail account to verify what you are seeing, and I can get verification code emails in a hotmail account without any problem.  I suspect there's something else going on with your hotmail account settings?  Could you try to create a new hotmail account and an associated user to try and narrow down this problem?

If it turns out it is a backend bug, then I will open a ticket with the Cognito team, but I suspect the problem somewhere else given that I just created a new cognito user pool, a new hotmail account and was unable to reproduce what you are seeing.

**Comment by serkandemirhan** [comment]
We are experiencing the same problem.Is there any update about it?
