### ISSUE TITLE
NSURLSession background upload support for s3

### ISSUE THREAD

**Issue by rahulgautam** [aws-amplify/aws-sdk-ios#25]
Hi I want to confirm that does aws-sdk-v2 supports background upload for files on amazon s3.
Because I see that's a very basic requirement as users won't stay in app until a long download finished.

If its not there please let me know how I could achive this, still using this SDK.
I'll be happy to contribute.

btw: Implemention with NSURLSession looks really nice. Thanks

**Comment by renjithn** [comment]
@yosuke-matsuda Any update on this ?  I can see a AWSURLSessionManager.m ? 
Can you confirm this?

**Comment by vbarshai** [comment]
Hi, required for me as well, please confirm that this is in v2 SDK (using pods)

**Comment by rromanchuk** [comment]
@cerupcat i will make a simple end to end project for everyone. I struggled through this for a while because apple's background transfer service is complex enough as it is, and  `aws-sdk-ios` doesn't really make it easier. As I mentioned before, this SDK is focused on the 1%, not developers who already know how to make a non-blocking network request.

**Comment by rromanchuk** [comment]
@yosuke-matsuda how do we set the ACL?  I don't see any interface in the API

**Comment by yosuke-matsuda** [comment]
Here are our current recommendations for using Amazon S3 with background transfer feature of the iOS.

`AWSS3TransferManager` is not designed to work in the background. Use `AWSS3PreSignedURLBuilder` to generate a pre-signed URL and upload/download data in the background with the native `NSURLSession`. Take a look at S3BackgroundTransfer Sample in our GitHub [repo](https://github.com/awslabs/aws-sdk-ios-samples). Also, more configuration options for `AWSS3PreSignedURLBuilder` are on their way.

**Comment by vbarshai** [comment]
Thank you @yosuke-matsuda  ; Are there plans to update the design of AWSS3TransferManager such that it supports background upload? Just want to avoid performing a work-around if this is something that's in the pipeline in the coming period.

**Comment by yosuke-matsuda** [comment]
Considering how the Foundation framework exposes background transfer APIs, currently it is quite challenging for us to provide an easy-to-use wrapper function as a part of `AWSS3TrasnferManager`. We may be able to provide some utility functions but are probably not able to drastically reduce the amount of glue code you have to write. This is the primary reason we decided to provide the sample code using `AWSS3PreSignedURL` with the native `NSURLSession` for background transfer instead of trying to integrate the feature directly into `AWSS3TransferManager`.

If you are looking for a nice wrapper for `NSURLSession`, [AFNetworking](https://github.com/AFNetworking/AFNetworking) provides some helpful utility functions for `NSURLSession`.

If you have ideas to enhance the background transfer integration, please share with us. We always appreciate ideas to improve our developer experience. Thanks!

**Comment by Ganidu** [comment]
@yosuke-matsuda 

I managed to integrate V2 sdk with NSUrlSession this upload works fine but i sometimes it doesn't 

1)Lets say if i uploded 4 video more than 500 MB then with the 5 th video it doesn't upload ,
2)application get stucked , 
3) Is there any way i can resume uploading

**Comment by hash3r** [comment]
@yosuke-matsuda how can we set the ACL to headers with presigned URL builder? May be you know some workaround without using putObjectAcl after uploading file

**Comment by vbarshai** [comment]
Hi @yosuke-matsuda ; we've went ahead and used AWSS3PreSignedURLBuilder ; getPreSignedURL , but it from what I could tell it uses Version-2 Authentication?? 
i.e. we're trying to upload to the new *Frankfurt bucket* and so I suppose to use Version-4 I need to append @"x-amz-algorithm":@"AWS4-HMAC-SHA256" to the request:

	AWSS3GetPreSignedURLRequest *getPreSignedURLRequest = [AWSS3GetPreSignedURLRequest new];
	getPreSignedURLRequest.bucket = currentBucketName;
	getPreSignedURLRequest.key = key;
	getPreSignedURLRequest.HTTPMethod = AWSHTTPMethodPUT;
	getPreSignedURLRequest.expires = [NSDate dateWithTimeIntervalSinceNow:3600];
	//Important: must set contentType for PUT request
	getPreSignedURLRequest.contentType = contentType;
	getPreSignedURLRequest.additionalAmzHeaders = @{@"x-amz-acl":@"public-read",
                                                    @"x-amz-algorithm":@"AWS4-HMAC-SHA256"};

then we use the following to get the URL:
[preSignedURLBuilder getPreSignedURL:getPreSignedURLRequest]

and further NSURLSessionUploadTask to upload. But it's not working. It responds as a success, the files aren't there though. Have you seen this before? Thank you in advance

**Comment by yosuke-matsuda** [comment]
`AWSS3PreSignedURLBuilder` currently supports only AWS Signature Version 2, meaning Frankfurt and Beijing regions are not supported. We are contacting the Amazon S3 team to find out if the service supports PreSigned URLs in these regions. The challenge is that SigV4 requires a payload (the body), but it is not always available for PreSigned URL use cases.

Could you create a new thread for SigV4 support for `AWSS3PreSignedURLBuilder`? We will follow up on this issue in that thread.

For other configuration options support including `ACL ` is in our backlog, and we prioritize accordingly.

Thanks,

**Comment by mcsio** [comment]
Any update on support for Version 4 signing?
