### ISSUE TITLE
Authentication error for unauthenticated user with private auth rule

### ISSUE THREAD

**Issue by TheBenck** [aws-amplify/aws-sdk-ios#2645]
**Which Category is your question related to?**
API (GraphQL) / Auth

**Amplify CLI Version** 
4.18.0

**What AWS Services are you utilizing?**
AppSync, Cognito, IAM, iOS SDK

**Provide additional details e.g. code snippets**
I created a books API with Amplify for an iOS app. I want the book table to have read access for both authenticated and unauthenticated users. Here's the schema:

```
type Book
  @model
  @searchable
  @auth(
    rules: [
      {allow: private, provider: userPools, operations: [read]},
      {allow: groups, groups: ["Admin"]}
    ]
  )
{
  id: ID!
  category: BookCategoryType!
  description: String
  groupsCanAccess: [String]!
  images: [Image!]
    @auth(rules: [
        {allow: groups, groupsField: "groupsCanAccess", operations: [read]},
        {allow: groups, groups: ["Admin"]}
    ])
  title: String!
}

...
```

However, when calling `fetch` from `AWSAppSyncClient`, I get the following error:
```
authenticationError(AWSMobileClient.AWSMobileClientError.notSignedIn(message: "User is not signed in, please sign in to use this API."))
```

The Cognito identity pool has `Enable access to unauthenticated identities` checked and there's an unauth IAM role. Also, when I call `AWSMobileClient.default().getAWSCredentials`, it returns credentials for the unauthenticated user.

What could be the problem?

Thank you

**Comment by palpatim** [comment]
> Is it possible to have the iOS app use both IAM and User Pools? I can only pass one provider to `AWSAppSyncClientConfiguration`. I'd like the unauthenticated user to have limited access and the authenticated user to have access based on their group

Hi @TheBenck. The AWSAppSync SDK can support multiple authorization modes simultaneously, as described [here](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#multi-auth). Bear in mind that the configuration and usage can become fairly complex, since you'll have to manually specify which configured client you want to use to make a particular GraphQL query. It's been a while since I looked at this in any detail, but if I recall correctly, you simply pass the configured `AWSMobileClient.default()` instance to the `AWSAppSyncClientConfiguration` for a particular authorization mode. `AWSMobileClient` reads its configuration from `awsconfiguration.json`, which can include configs for both UserPools and IAM.
