### ISSUE TITLE
Display social identity provider domain instead of amazoncognito or user's domain during federated sign in

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/aws-sdk-ios#2857]
**Which AWS Services is the feature request for?**
Auth

**Is your feature request related to a problem? Please describe.**

When I sign in with Google using Amplify-iOS, iOS alert modal shows my website domain instead of the domain of the social identity provider. I have tried with Speechify app and their alert displays `google.com` domain instead of their domain.
<img width="418" alt="87235739-0bdf9680-c394-11ea-8278-a5e793f96506" src="https://user-images.githubusercontent.com/6880939/87708423-8ffc9a00-c757-11ea-98cf-e0cd598337c8.png">

**Describe the solution you'd like**

I would it to show social identity provider instead of my website domain. 
According to @wooj2, signInRedirectUrl is being passed and thus shows up in the alert modal. Can social identity provider domain be passed during social idp federated login?

![87200792-22152600-c2b2-11ea-9410-545140824586](https://user-images.githubusercontent.com/6880939/87708178-29777c00-c757-11ea-8bcf-d79ae3d7d603.png)

**Additional context**

This is the second item I wrote in https://github.com/aws-amplify/amplify-ios/issues/634#issuecomment-657146879

**Comment by wooj2** [comment]
Hi @Jun711,

Unfortunately, as far as I know, changing the UIAlertView to show social identity provider instead of your website domain is something that we do not have control over (See https://github.com/aws-amplify/amplify-ios/issues/634#issuecomment-659154823 ).  Given our current understanding of the system, we are unable to take this as a feature request and/or bug report.

Thank you for your understanding.
