### ISSUE TITLE
iOS: Can we track Rich Push Notification using Pinpoint App Analytics?

### ISSUE THREAD

**Issue by sheethaljc** [aws-amplify/aws-sdk-ios#2923]
We need to track whether Rich Push received in App side.

Is possible to send events through iOS Native AWS SDK?
Or 
Any REST APIs there to send events?

**Comment by sheethaljc** [comment]
Please let us know any updates on this.

**Comment by lawmicha** [comment]
Hi @sheethaljc, on the iOS side, from my understanding since rich push notifications is a feature built using [Notification Content App Extension](https://developer.apple.com/documentation/usernotificationsui/customizing_the_appearance_of_notifications), you will not be able to incorporate the AWS SDK into that target, thus you won't be able to use the AWS Pinpoint SDK to record events about your notification occuring. The AWS SDK currently supports iOS apps only, not app extensions. See https://github.com/aws-amplify/aws-sdk-ios/issues/2978 for more details regarding the feature request.

**Comment by lawmicha** [comment]
Closing as dedup to https://github.com/aws-amplify/aws-sdk-ios/issues/2978, please let us know if you more questions

**Comment by dandreiolteanu** [comment]
Hello, jumping into this discussion even if the ticket is closed. 

I would like to ask if it's now possible to send an Analytics event from the `NotificationAppExtension`, basically we want to track when a notification is received on the app side. 

Thanks!
