### ISSUE TITLE
Getting unidentified random user from Cognito pool

### ISSUE THREAD

**Issue by RajAggrawal0507** [aws-amplify/aws-sdk-ios#2960]
I am using AWSCognitoIdentityProvider version 2.13.3. 
On the app, launch created initialized the Cognito using below code

 let serviceConfiguration = AWSServiceConfiguration(region: "###PoolRegionID", credentialsProvider: nil)
  
        // create pool configuration
        let poolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: "###ClientID",
                                                                        clientSecret: "###Secret ID",
                                                                        poolId: "###PoolRegionID")
        
        // initialize user pool client
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: poolConfiguration, forKey:"UserPool")

Now create Pool
let pool = AWSCognitoIdentityUserPool(forKey: ""UserPool")

pool.currentUser() returns a dummy user with UDID in username field

**To reproduce:**

1. Sign in the user with username and password.
2. Delete the app 
3. Re-install the app
4.  call the pool.currentUser()
5. currentUser return a user object

**Expected behaviour:**
currentUser method should returns nil as app is re-installed and no user is logged into app.

#AWSCognitoIdentityProvider #bug

**Comment by DongQuanRui** [comment]
Hi, @RajAggrawal0507 
So when you are signed in and fetch the credential, it will be stored in the keychain. So even you delete the App, the user values persist.

**Comment by palpatim** [comment]
For customers who have encountered this in the past, we've recommended tracking individual installations by writing a flag to local storage that gets cleared when uninstalling (as opposed to the keychain, which is retained even after app uninstall).

For example, you could write a `hasLaunchedBefore` flag to UserDefaults, and check for that flag at startup. If the flag does **not** exist, you would remove previous values with `pool.clearAll()`, and then write the `hasLaunchedBefore` flag. On subsequent startups, since the flag exists, Cognito would pull from previously persisted values in the keychain.

**Comment by RajAggrawal0507** [comment]
Thanks for the update. 
it helps me a lot.
