### ISSUE TITLE
possible to refresh credentials using AWSS3TransferUtility yet?

### ISSUE THREAD

**Issue by fantapop** [aws-amplify/aws-sdk-ios#3385]
Our app uses STS temporary credentials which are passed down from our api to enable file uploads to an S3 bucket.  Our backend runs on ECS which assumes a role during launch to provide its runtime permissions.  We're then using sts.assumeRule to get a more restricted set of credentials for uploading the files.  Because of role chaining, our session is limited to 1 hour. see here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html

This limits our ability to upload files that may take longer than 1 hour as well as our ability to retry for periods longer than this without completely starting over.

I've found various references suggesting this is a limitation of AWSS3TransferUtility, for example, this 2015 blog post: https://aws.amazon.com/blogs/mobile/amazon-s3-transfer-utility-for-ios/

The suggestion there is to use AWSTransferManager which does not support background uploads.  I'm wondering if this is still the case in 2021?  If so, is there some technical difficulty preventing a solution such as a calling out to a credential provider for each part prior to upload?  Thanks

**Comment by palpatim** [comment]
@fantapop As of right now, we don't have a good solution for this. TransferManager was deprecated a couple of years ago and removed earlier this year, and as you say, didn't support background operations.

The technical challenge on the iOS front is that, as far as we know, a background task cannot call back into the app for credentials (see https://developer.apple.com/forums/thread/28713 for a relevant discussion), which means that we have to enqueue a background task with a presigned URL. As you note, AWS role-based credentials used to generate to the presigned URL are only valid for a maximum of one hour, which means presigned URLs expire after an hour, even if you specify a longer duration when you create the URL.

**Comment by palpatim** [comment]
Related to https://github.com/aws-amplify/amplify-ios/issues/638

**Comment by rromanchuk** [comment]
@fantapop i use `AWSS3TransferUtility` extensively  in similar fashion.  Clients are granted access via authenticated _and_ unauthenticated federated identity pools, with IAM roles for each, that are responsible granting appropriate permissions for direct-to-bucket accelerated s3 uploads.   

For the "authenticated" role, I have created a `DeveloperAuthenticatedIdentityProvider` which handles the fetching and refreshing of a user already authenticated (ours), the sdk automatically fetches/refreshes by old fashion REST to our backend, which then mints (or refreshes if already exists) the credentials with token and identity id. 

There are settings for session length for my cognito roles in IAM console and there is also  a token_duration i can pass as a property when the backend generates the token via `get_open_id_token_for_developer_identity`

I have a hunch this is going to be a very simple fix for you. Unfortunately these service level SDKs become difficult in terms of documentation and information passing because... of reasons i complain about all the time so i wont here.

`AWSS3TransferUtility` is most definitely not deprecated (or at least not declared so in the source), and just generally, there is a lot of confusion and conflation around backgrounding but it's not really unique to this SDK. 

I would be highly suspicious of this claim below, it sounds wrong and smelly. Or maybe confusing non-user initiated backgrounding. It literally doesn't make any technical sense either. If your token expires and you're within your own user defined retry limit, just refresh the credentials, that's something offloaded to the cognito provider. I'll take a look at the source, and willing make a repo with the most ridiculous use case i can think of.

> Behind the scenes, the Transfer Utility generates Amazon S3 pre-signed URLs and uses them to enable background transferring. Using Amazon Cognito Identity, you receive AWS temporary credentials that are valid for up to 60 minutes. It is not possible to generate S3 pre-signed URLs that last longer than 60 minutes. Due to this limitation, the Transfer Utility enforces 50-minute transfer timeouts (10-minute buffer for reducing AWS temporary credential regenerations). After 50 minutes, you receive a transfer failure.

**Comment by rromanchuk** [comment]
Sounds like the limitation is just do to Role chaining.   Here's pseudo code of how i'm doing it.

### Backend, ruby client sdk, ec2-instance IAM role

```ruby
# PUT /sessions/cognito
client.get_open_id_token_for_developer_identity({
      identity_pool_id: IDENTITY_POOL_ID, # required
      identity_id: user.aws_identity_id, # this becomes a create call if nil
      logins: { # required
        developer_provider_name => user.id # "Our" uuid
      },
      token_duration: 86400
 })

#=> {identity_id: "us-east-1-blahlbhaljfd"  token: "jwt payload blahblah"}
 ```

### Ios client

``` swift
// Interface where cognito will hand over control when creds are needed, chance for you to make your own REST to your own APIs 
class DeveloperAuthenticatedIdentityProvider : AWSCognitoCredentialsProviderHelper {
    // Automatically called when a service configured with dev auth needs wants use a service
    // or needs to refresh expired creds
    override func token() -> AWSTask<NSString> {
        let completionSource = AWSTaskCompletionSource<NSString>()

        let req = APIManager.shared.manager.request("PUT /sessions/cognito")
        APIManager.shared.call(req) { (response: AFDataResponse<CognitoCredential>) in
            switch response.result {
            case let .success(credential):
                // credential.id  -> "us-east-1-blahlbhaljfd"
                completionSource.set(result: credential.token as NSString)
            case let .failure(error):
                completionSource.set(error: error)
            }
        }
        return completionSource.task
    }

    override func logins() -> AWSTask<NSDictionary> {
        guard MyCompanyAuthManager.thisUserIsAlreadyAuthenticatedAndHasValidSession else { return AWSTask(result: nil) }
        return super.logins()
    }
}
```


```swift
func setupCognitoCredentials() {
        
        let awsConfig = Config.shared.aws
        /*
         AWS Cognito
         */
        let devAuth = DeveloperAuthenticatedIdentityProvider(regionType: C.Aws.config.region.aws_regionTypeValue(), identityPoolId: C.Aws.config.cognitoPool, useEnhancedFlow: true, identityProviderManager: nil)
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: C.Aws.config.region.aws_regionTypeValue(), identityProvider: devAuth)

        // Set the default service configuration to the cognito pool region
        let configuration = AWSServiceConfiguration(region: C.Aws.config.region.aws_regionTypeValue(), credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        
        /*
         AWS S3
         */
        // Setup transfer utility for checkin uploads
        let myBucketConfig = AWSServiceConfiguration(region: C.Aws.config.s3.myBucket.region.aws_regionTypeValue(), credentialsProvider: credentialsProvider)
        let s3Conf = AWSS3TransferUtilityConfiguration()
        s3Conf.isAccelerateModeEnabled = true
        s3Conf.retryLimit = 15
        s3Conf.bucket = C.Aws.config.s3.myBucket.name

        AWSS3TransferUtility.register(with: checkinsConfig!, transferUtilityConfiguration: s3Conf, forKey: C.Aws.config.s3.myBucket.name)
       
    }
```

More chatter on expiration depending who is granting the creds https://stackoverflow.com/a/57792699/775762

**Comment by harsh62** [comment]
Closing the issue as it seems to have been answered.
