### ISSUE TITLE
Failed to Build With Carthage on XCode 12.4

### ISSUE THREAD

**Issue by aiartsev** [aws-amplify/aws-sdk-ios#3390]
**Describe the bug**
Failing to build after upgrading to XCode 12.4

**To Reproduce**
1. Run `carthage update --platform iOS --no-use-binaries`

**Observed Behavior**
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/russianally/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/aws-sdk-ios/2.22.0/Build/Intermediates.noindex/ArchiveIntermediates/AWSAPIGateway/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSAPIGateway.framework/AWSAPIGateway /Users/russianally/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/aws-sdk-ios/2.22.0/Build/Products/Release-iphonesimulator/AWSAPIGateway.framework/AWSAPIGateway -output /Users/russianally/Projects/Audish/Dependencies/Carthage/Build/iOS/AWSAPIGateway.framework/AWSAPIGateway

**Expected Behavior**
To complete the build.

**Stack Trace**
Log:
[carthage-xcodebuild.8NmtHl.log](https://github.com/aws-amplify/aws-sdk-ios/files/5889047/carthage-xcodebuild.8NmtHl.log)

**Code Snippet**
Please provide a snippet of the code causing the issue or how you are using the service that has the bug.

**Environment(please complete the following information):**
 - SDK Version: 2.22.0
 - Dependency Manager: Carthage
 - Swift Version : 5.3.2
 - Xcode Version: 12.4

**Additional context**
I've been able to build using the following script, but then I receive an error when linking inside the XCode itself. Attaching the script and the error screenshot below.

```
set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.

CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

![image](https://user-images.githubusercontent.com/1669221/106177534-65b07e00-6177-11eb-9e92-5c53c3de43c7.png)

**Comment by palpatim** [comment]
The build script is only part of the problem--it removes the unsupported arm64 arch from the simulator binary. The next step is to strip the other architectures from the fat binary by using the "strip frameworks" script as noted [in the Carthage section of the README](https://github.com/aws-amplify/aws-sdk-ios#carthage)

We are in the process of releasing support for XCFrameworks for all of the service SDKs except AWSLex, which should solve this problem in a more idiomatic way.

**Comment by palpatim** [comment]
@aiartsev

We have added the Xcode 12.2, 12.3, and 12.4 build tags to our `carthage-build.sh` script. You can feel free to use it as a basis for your own build scripts, bearing in mind that you will still need to strip the fat binaries if you use the SDK version 2.22.0 or below.

However, you don't really need it because as of 2.21.1, we distribute the binaries as XCFrameworks. :) Please see [Carthage installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframeworks-recommended) or [XCFramework installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframework-setup) in the README for more info.

Do note that AWSLex is not currently published as a binary framework--it ships with binary frameworks that aren't amenable to XCFramework generation. We're exploring options there, but for now, you can either consume them from source, or use version 2.22.0 or earlier.

Please let us know if you have any further issues.
