### ISSUE TITLE
Could not find module 'AWSMobileClient' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7

### ISSUE THREAD

**Issue by mstaylor** [aws-amplify/aws-sdk-ios#3469]
**Describe the bug**
Using carthage xc frameworks and compiling for simulator, I get the following:

Could not find module 'AWSMobileClient' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7

**To Reproduce**
Follow carthage integration steps detailed in the WIKI and try to build for a simulator target.

**Observed Behavior**
See above
**Expected Behavior**
Simulator builds should be successful.

**Stack Trace**
Fails at import during compilation phase

**Code Snippet**
import Foundation
import AWSMobileClient
import GameKit

**Unique Configuration**
Carthage integration as directed by the wiki
**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient, Pinpoint, Cognito
**Screenshots**
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/3780235/110960835-29973e00-831d-11eb-907a-2b0574057880.png">

**Environment(please complete the following information):**
 - SDK Version:  2.23.1
 - Dependency Manager: Carthage
 - Swift Version : Swift 5
 - Xcode Version: Version 12.4 (12D4e)

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators: all simulator builds fail

**Additional context**

**Relevant Console Output**

**Comment by brennanMKE** [comment]
@mstaylor I have reproduced this build locally with the same version of Xcode and a fresh install of Carthage. I also built with the Carthage binaries for both a SwiftUI and UIKit app and ran the unit tests for both projects. I've compressed and included these sample projects which are placed in the Carthage directory with the Cartfile. The `Carthage/Build` directory is below it and the Xcode projects have relative references to each of the required frameworks. (see links below)

What you will see is the contents of the XC Framework include 2 variants.

* ios-arm64_armv7
* ios-arm64_i386_x86_64-simulator

What I see is the first one is the variant for device builds which include slices for arm64 and armv7. The 2nd one is the variant for the simulator which includes arm64, i386 and x86_64. Since the deployment target is set to 11.4 there is no need for 32-bit slices so i386 is not needed but it can still be included in the variant.

To confirm which architecture slices are in the binaries I ran the `lipo` command.

`find . -name AWSMobileClient -exec lipo -info {} \; `

And here are the results which include the dSYM files:

```sh
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_i386_x86_64-simulator/AWSMobileClient.framework/AWSMobileClient are: x86_64 i386 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/AWSMobileClient.framework.dSYM/Contents/Resources/DWARF/AWSMobileClient are: x86_64 i386 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_armv7/AWSMobileClient.framework/AWSMobileClient are: armv7 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_armv7/dSYMs/AWSMobileClient.framework.dSYM/Contents/Resources/DWARF/AWSMobileClient are: armv7 arm64 
```

If the build build products created by Carthage are missing the x86_64 slice from the simulator binary that would be the problem. This is the Intel binary which is used for testing on an Intel Mac. For a newer Mac running Apple Silicon the arm64 variant for the iOS Simulator would be used. If the build products produced by Carthage are lacking the Intel slices for the iOS Simulator perhaps the build products were created with an M1 Mac. My MacBook has the Intel chip and these are the build products which were created with Carthage.

Can you confirm your folder structure is the same under `Carthage/Build` for AWSMobileClient as well as the variants and architecture slices?


* [UIKit.zip](https://github.com/aws-amplify/aws-sdk-ios/files/6133802/UIKit.zip)
* [SwiftUI.zip](https://github.com/aws-amplify/aws-sdk-ios/files/6133803/SwiftUI.zip)
* [AWSMobileClient.xcframework.zip](https://github.com/aws-amplify/aws-sdk-ios/files/6133805/AWSMobileClient.xcframework.zip)

**Comment by mstaylor** [comment]
@brennanMKE - I tried replacing my AWSMobileClient carthage xcframework with the zip provided and the issue remained.

StaylorsTemple2:Build mstaylor$ find . -name AWSMobileClient -exec lipo -info {} \;
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_i386_x86_64-simulator/AWSMobileClient.framework/AWSMobileClient are: x86_64 i386 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/AWSMobileClient.framework.dSYM/Contents/Resources/DWARF/AWSMobileClient are: x86_64 i386 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_armv7/AWSMobileClient.framework/AWSMobileClient are: armv7 arm64 
Architectures in the fat file: ./AWSMobileClient.xcframework/ios-arm64_armv7/dSYMs/AWSMobileClient.framework.dSYM/Contents/Resources/DWARF/AWSMobileClient are: armv7 arm64 

Perhaps there is some build setting that should be validated.  Can you provide the build settings you have that result in a successful simulator build?

**Comment by mstaylor** [comment]
@brennanMKE  - actually I've confirmed this is not an issue.  My problem was related to cmake and simulator vs. device targets.  Thanks for looking into this issue.
