### ISSUE TITLE
manage multiple user session Cognito authentication

### ISSUE THREAD

**Issue by VidhiDifferenz** [aws-amplify/aws-sdk-ios#3534]
I need to fetch the previously logged-in user's session id. For that, I'm using below code -

```
    appDelegate.poolUser?.getUser("username").getSession().continueWith(block: { (task) -> Any? in
                            if let result = task.result {
                                callback(result.idToken?.tokenString, nil)
                            } else {
                                callback(nil, task.error)
                            }
                            return task
                        })
```

Now, on getSession, it's reauthenticating the user with startPasswordAuthentication delegate method but never returning the user session inside the block.

I have also added below delegate method for the authentication which is being called after getSession. But not sure how to handle that with the getSession call.

```
    public func getDetails(_ authenticationInput: AWSCognitoIdentityPasswordAuthenticationInput, passwordAuthenticationCompletionSource: AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails>) {
        print("getDetails")
        self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource
    }
```

**Comment by lawmicha** [comment]
Hi @VidhiDifferenz, could you provide more details for us reproduce/understand the problem better?

1. How did you set up the backend? Could you describe the authentication you case you have set up for your users? What happens when they go through your sign up/sign in flows?
2. What SDK version are you using?
3. Amplify CLI version, if any, are you using and steps taken?
4. Can you clarify, is the `continueWith` block executed but falling into the `else` block and you do not get the `task.result` back?
