### ISSUE TITLE
AWSS3TransferUtility Does not Appear to Work for Buckets with Hyphens

### ISSUE THREAD

**Issue by jonathantorrens425** [aws-amplify/aws-sdk-ios#3573]
**Describe the bug**
When attempting to use the iOS AWSS3TransferUtility SDK to upload files to S3, the uploads fail for buckets that have hyphens in the name. This appears to be an issue that other developers have run into when using the SDK. It does work with buckets that have no hyphens in the bucket name.

**To Reproduce**
1. Attempt to upload to a bucket with hyphens in the bucket name using the AWSS3TransferUtility

**Observed Behavior**
The upload fails with the following error:

`Error Domain=com.amazonaws.AWSS3PresignedURLErrorDomain Code=13 "For your bucket to work with transfer acceleration, the bucket name must conform to DNS naming requirements and must not contain periods." UserInfo={NSLocalizedDescription=For your bucket to work with transfer acceleration, the bucket name must conform to DNS naming requirements and must not contain periods.}`

**Expected Behavior**
The upload will succeed.

**Stack Trace**
`Error Domain=com.amazonaws.AWSS3PresignedURLErrorDomain Code=13 "For your bucket to work with transfer acceleration, the bucket name must conform to DNS naming requirements and must not contain periods." UserInfo={NSLocalizedDescription=For your bucket to work with transfer acceleration, the bucket name must conform to DNS naming requirements and must not contain periods.}`

**Code Snippet**
`
let result = transferUtility.uploadUsingMultiPart(fileURL: url,
                                                                   bucket: bucket,
                                                                   key: id,
                                                                   contentType: contentType,
                                                                   expression: expression,
                                                                   completionHandler: awsCompletion)`

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
`AWSS3TransferUtility`

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.24.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.4
 - Xcode Version: 12.5

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - iOS Version: 14.5.1

**Comment by palpatim** [comment]
Can you clarify? You say "hyphens", but the error is about "periods". "Hyphens" (that is, the `-` character or ASCII 0x2d) are supported in bucket names, which we prove every time we run our TransferUtility integration tests (which use bucket names containing hyphens).

Periods, on the other hand (that is, the `.` character or ASCII 0x2e) are *not* supported in bucket names. This is because TransferUtility uses "virtual host" style addressing for buckets, and the wildcard SSL certificate that protects the endpoint doesn't work with hostnames of arbitrary depth (that is, the cert supports `*.us-east-1.s3.amazonaws.com`, but the `*` can't include dots). 

You can see a bit more discussion, and pointers to more docs, in the [2.17.0 release notes](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.17.0).

If you have a different experience, can you post more detailed repro steps, including your bucket name and the SDK configuration you're using?

**Comment by jonathantorrens425** [comment]
Hi, thanks for the quick response. The error does indeed state that periods can't be used, but in our experience, the `-` character is what is triggering the error. We tried uploading to a bucket with no hyphens/dashes, and one with hyphen/dashes in the name. The bucket with hyphens/dashes returned the above error.

The upload that failed on a bucket called `cognoa-dev` but succeeded on a bucket called `cognoaiostest`. Both buckets were otherwise configured identically.

**Comment by palpatim** [comment]
@jonathantorrens425 As mentioned, dashes are definitely supported, and I've proven that within the past hour by running integration tests against buckets with dashes in the name. If you can provide more details around configuration, API invocations, etc, we can try to troubleshoot further.
