### ISSUE TITLE
Clarify when to use AWSS3TransferUtility vs Amplify Storage?

### ISSUE THREAD

**Issue by jamescrowley** [aws-amplify/aws-sdk-ios#3627]
Can you clarify when someone should use the AWSS3TransferUtility and when we should be using the Amplify.Storage mechanism, when implementing a new project?

Are there any functionality differences between them, or limitations on how many files you can queue for background upload?

The examples for AWSS3TransferUtility seem to require referencing the AWSMobileClient (https://github.com/awslabs/aws-sdk-ios-samples/blob/main/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/AppDelegate.swift). 

According to your documentation (https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios) that appears to be deprecated. 

However, the Amplify storage documentation has far less information about whether this works for background uploads, managing transfers across app restarts etc. 

Am I better off using AWSS3TransferUtility for now, and referencing the AWSMobileClient?

**Comment by brennanMKE** [comment]
@jamescrowley For now you will be better off using Transfer Utility for background transfers. As for the number of pending requests the primary factor to consider is whether the transfers will complete before your pre-signed URLs expire since the OS will be using them when the transfer can be processed. If you have the background with [allowsCellularAccess] set to false on [URLSessionConfiguration] a device with pending transfers may not be connected to WiFi before the pre-signed URLs expire. If this happens the app could monitor for this condition and set up another transfer.

If you have more questions please post them here.

[allowsCellularAccess]: https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1409406-allowscellularaccess
[URLSessionConfiguration]: https://developer.apple.com/documentation/foundation/urlsessionconfiguration

**Comment by jamescrowley** [comment]
@brennanMKE thanks - good to know. Is there any chance you can clarify exactly what the limitations currently are for amplify storage for background transfers? We currently have an amplify storage implementation, and just want to understand what issues to look out for so we can decide if it will be a problem for our use case

**Comment by palpatim** [comment]
@jamescrowley 

The biggest limitation right now is that Amplify Storage doesn't support "reattaching" to in-process tasks when resuming from background. We're tracking that in an open [feature request](https://github.com/aws-amplify/amplify-ios/issues/1102), but we don't have any information to add right now.

**Comment by diegocstn** [comment]
Closing in favour of https://github.com/aws-amplify/amplify-ios/issues/1102.
