### ISSUE TITLE
Downloading file from S3 does not exist locally before the end of the download

### ISSUE THREAD

**Issue by mregnauld** [aws-amplify/aws-sdk-ios#3644]
In my iOS app, I download an audio file from an AWS S3 bucket using the following:

```Swift
// some initial configuration:
let transferUtilityConfiguration: AWSS3TransferUtilityConfiguration = AWSS3TransferUtilityConfiguration()
let serviceConfiguration = AWSServiceConfiguration(
	region: AWSRegionType.EUCentral1,
	credentialsProvider: AWSMobileClient.getInstance())
AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration

// transfer utility :
AWSS3TransferUtility.register(
	with: serviceConfiguration!,
	transferUtilityConfiguration: transferUtilityConfiguration,
	forKey: "testkey") { (error) in
        // some stuff...
}

// destination URL:
let caches = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)
if (caches.first != nil)
{
    let urlAudio = caches.first!.appendingPathComponent("mymusic.ogg", isDirectory: false)

    // download a file:
    AWSS3TransferUtility.default().download(
	    to: urlAudio,
	    bucket: "my-test-bucket",
	    key: "mymusic.ogg",
	    expression: getProgressionExpression(),
	    completionHandler: nil).continueWith { [weak self] task in
            // some stuff...
    		return nil
	    }
}

private func getProgressionExpression() -> AWSS3TransferUtilityDownloadExpression
{
	let expression: AWSS3TransferUtilityDownloadExpression = AWSS3TransferUtilityDownloadExpression()
	expression.progressBlock = {(task, progression) in DispatchQueue.main.async {
        print("progression: \(progression.fractionCompleted)")
	}}
	return expression
}
```

The download runs smoothly and I can track the downloading progress without any issue. When the download is complete, I got my `music.ogg` file at the expected URL.

That said, I want to access the file ***while*** it's downloading, since I need to play the music while it's downloading.

And when I check if the file exists, using the following:

```Swift
FileManager.default.fileExists(atPath: urlAudio.path)
```

it always returns `false` while it's downloading. It only returns `true` when the download is complete. Same if I check the file length (always equal to `0` while downloading, only equal to the actual file size when the download is complete).

Also, I only get that problem on iOS and not on Android even though I use the same API.

Why do I have that behavior?
How can I access the file while downloading?

Thanks.

### **EDIT**

Correct me if I'm wrong, but after more investigation, it appears that the file is being downloaded in a temporary folder, `<app_directory>/Library/Caches/com.apple.nsurlsessiond/Downloads/<app_name>/`, and **_then_** is moved to its final destination once downloaded.

But... why?? How am I supposed to stream my audio file then?

**Environment:**
 - SDK Version: 2.22.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information:**
 - Device: iPhone 11
 - iOS Version: iOS 14.6

**Comment by palpatim** [comment]
There are a couple of reasons NSURLSession does this, but a primary one is to make its downloads "atomic"--that is, to ensure that you aren't operating on partially downloaded files. In order to access the file while it's playing, you'd need to use a streaming API rather than a `download` API. 

To my recollection AWSTransferUtility doesn't support streaming tasks. Its primary use case is for uploading and downloading full files with background support, not providing live access during the transfer. One workaround would be to not use AWSTransferUtility for the download. Instead, you could use AWSPresignedURLBuilder to obtain a presigned URL for the music file you wish to download (see example in our [integration tests](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSS3Tests/AWSS3PreSignedURLBuilderTests.m#L294-L302)), then use an [NSURLSession](https://developer.apple.com/documentation/foundation/nsurlsession) download or data task, with a custom [delegate](https://developer.apple.com/documentation/foundation/nsurlsessiondownloaddelegate) to get [notified of new bytes](https://developer.apple.com/documentation/foundation/nsurlsessiondownloaddelegate/1409408-urlsession) as they arrive on the task. Once you have those bytes in hand, you can send them to your audio processing routine for playback.

We have an open [RFC](https://github.com/aws-amplify/amplify-cli/issues/6896) for Media use cases, including streaming, so please feel free to comment on that with details of your use case and we'll consider it for future work in Amplify.

Hope this helps.

**Comment by mregnauld** [comment]
@palpatim Thanks for your detailed answer.
That's what I tried recently on Android and it works great, even better than the AWS SDK.
I'm currently working on it on iOS, and I'll check what you suggested.

**Comment by mregnauld** [comment]
@palpatim Do you have any example of `AWSPresignedURLBuilder ` in Swift? I can't find any.

**Comment by diegocstn** [comment]
@mregnauld let us know how that goes, and feel free to comment on the open RFC for [Media](https://github.com/aws-amplify/amplify-cli/issues/6896).

**Comment by mregnauld** [comment]
OK, it's working now!
First, I followed that [blog post](https://medium.com/@madhurjain874/how-to-integrate-awss3-in-your-ios-swift-application-6492e4d2f246) to create a presigned URL each time I need to download a file (even if it's the same file, even if I need to resume a download), and then I created my own HTTP client using a `URLSession` and a `URLSessionDataTask`, that help me download a file by small blocks, that I save to a new file if it doesn't exists, or append to an existing file.
Thanks for your help!
