### ISSUE TITLE
Can you sign in with Hosted UI and not have the browser cache your credentials? 

### ISSUE THREAD

**Issue by jarvis32123** [aws-amplify/aws-sdk-ios#3647]
Is there a way to specify the browser to not cache the login credentials when using the sign in with hosted UI function?

Here is the code I use to launch and log in via hosted UI:

```
let hostedUIOptions = HostedUIOptions(scopes: ["openid", "email", "profile", "phone"], identityProvider: "YOUR-PROVIDER")

AWSMobileClient.default().showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in
    if let error = error as? AWSMobileClientError {
        print(error.localizedDescription)
    }
    if let userState = userState {
        print("Status: \(userState.rawValue)")
    }
}
```

I do know that you can sign out and clear that browser cache, but we have found sometimes it doesn't clear it. And also, there is a bigger issue: if the user uninstalls the mobile app without logging out, the next time they install it and go to log in, those credentials will still be cached. There is no callback to run any code when a user uninstalls an iOS/Android app.

**Comment by palpatim** [comment]
On iOS 13 and above, you can pass [`signInPrivateSession` to your HostedUIOptions](https://github.com/aws-amplify/aws-sdk-ios/blob/2ce94a7fda175ed6ffd86c993b0ace219b926ac2/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift#L125) to set the underlying `ASWebAuthenticationSession.prefersEphemeralWebBrowserSession` flag. This will cause the HostedUI session to login with a private cookie store, rather than using the system's shared Safari cookie store. (It has the added benefit of suppressing the "YourAppName wants to use yourhostedui.domainname.com" alert notifications in some cases as well.)

Hope this helps.
