### ISSUE TITLE
Getting an Error on iPhone 12/ 12 Pro (running on iOS 14.6)

### ISSUE THREAD

**Issue by androidshivam** [aws-amplify/aws-sdk-ios#3669]
**Description of bugs:** Unhandled Exception: SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)

**To Reproduce:** While installing the app in iOS 12 & 12Pro

**Expected Behavior:** Initialise the AWS plugins and fetch the current session of user null if User is not signin else gives null

**Stack Trace:**

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)
#0      AmplifyAuthCognitoMethodChannel.fetchAuthSession (package:amplify_auth_cognito/method_channel_auth_cognito.dart:239:7)
<asynchronous suspension>
#1      AmplifyAuthCognito.fetchAuthSession (package:amplify_auth_cognito/amplify_auth_cognito.dart:113:17)
<asynchronous suspension>
#2      CognitoService.isSignedIn (package:total_vision/services/cognito_service.dart:470:21)
<asynchronous suspension>
#3      CognitoService.configureAmplify (package:total_vision/services/cognito_service.dart:151:20)
<asynchronous suspension>

**Code Snippet:**

Future<bool> isSignedIn() async {
    final session = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true));
    if(session.isSignedIn){
      await getUserData();
      await fetchSession();
      unawaited(Future.delayed(Duration.zero, locator<AppSyncService>().queryAll));
    }
    return session.isSignedIn;
  }

**Environment(please complete the following information):**

SDK Version: 2.2.3
Dependency Manager: CocoaPods version 1.10.1
Xcode Version: Xcode 12.5.1, Build version 12E507
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-26 at 11 31 25](https://user-images.githubusercontent.com/45711013/126940419-f912683b-ff64-4d5e-bce2-d0f5c93d6bd7.png)

**Device: iPhone 12 & iPhone 12 Pro**
iOS Version: 14.6

**Comment by diegocstn** [comment]
@androidshivam In order to diagnose the issue it'd be helpful for us to have following information:

**Describe the bug**
_A clear and concise description of what the bug is. Please be as detailed as possible and help us help you._

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_

**Observed Behavior**

**Expected Behavior**
_A clear and concise description of what you expected to happen._

**Stack Trace**
_Please provide a stack trace if applicable e.g. a crash is occurring._

**Code Snippet**
_Please provide a snippet of the code causing the issue or how you are using the service that has the bug._

**Unique Configuration**
_If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting._

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Environment(please complete the following information):**
 - SDK Version: _[e.g. 2.6.29]_
 - Dependency Manager: _[e.g. Cocoapods, Carthage]_
 - Swift Version : _[e.g. 4.0]_
 - Xcode Version: _[e.g. 11.4]_

**Device Information (please complete the following information):**
 - Device: _[e.g. iPhone6, Simulator]_
 - iOS Version: _[e.g. iOS 11.4]_
 - Specific to simulators:

**Additional context**
_Add any other context about the problem here like your specific use case._

**Comment by royjit** [comment]
@androidshivam  Are you using Amplify Flutter library?

**Comment by androidshivam** [comment]
Yes

**Comment by royjit** [comment]
Closing this since you already have a Github issue https://github.com/aws-amplify/amplify-flutter/issues/747 with Flutter team
