### ISSUE TITLE
Embed AWSCore inside Framework cause crash

### ISSUE THREAD

**Issue by SilvioPulitano** [aws-amplify/aws-sdk-ios#3809]
Hi,

I try to embed AWSCore inside my own xcframework. I have a crash at runtime only on Device, works fine on simulator.
Seems to be a code signature problem.

```
dyld: Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /private/var/containers/Bundle/Application/98856486-8AE4-4ED9-B2E9-8F64C2386875/TadamSDKSample.app/Frameworks/TadamSDK.framework/TadamSDK
  Reason: no suitable image found.  Did find:
  /private/var/containers/Bundle/Application/98856486-8AE4-4ED9-B2E9-8F64C2386875/TadamSDKSample.app/Frameworks/TadamSDK.framework/Frameworks/AWSCore.framework/AWSCore: code signature in (/private/var/containers/Bundle/Application/98856486-8AE4-4ED9-B2E9-8F64C2386875/TadamSample.app/Frameworks/Tadam.framework/Frameworks/AWSCore.framework/AWSCore) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

```
I use Xcode 12.5.1 and SPM. It works fine with other SPM library.
I have one project with 2 targets: The framework and the sample.

![Capture d’écran 2021-10-07 à 19 08 07](https://user-images.githubusercontent.com/83234816/136432300-0be3ca52-0fbe-4653-985f-bdb5064b4034.png)

**Comment by Praphin** [comment]
Similar issue happening in XCode 13.
Crashing due to AWSCore not found. Any help

<img width="889" alt="Screenshot 2022-07-11 at 9 50 59 PM" src="https://user-images.githubusercontent.com/6714897/178311331-123ac2cb-4810-4e19-8a57-c4c801e5d054.png">
<img width="892" alt="Screenshot 2022-07-11 at 9 51 12 PM" src="https://user-images.githubusercontent.com/6714897/178311352-0dc6d356-f7ee-491e-9811-33fd78162835.png">
4
