### ISSUE TITLE
SignInWithApple native support like Firebase & Realm both have.

### ISSUE THREAD

**Issue by philipheinser** [aws-amplify/aws-sdk-ios#4019]
Are there any plans to support SignIn with Apple other then having to open a hosted website and giving the user a really bad experience and having trouble when going through the app store review becouse apple sometimes rejects apps becouse they use the web flow?

**Comment by thisisabhash** [comment]
Hello,
Currently this is not supported. We have added this as an item in our feature requests and will post here with more information.

**Comment by enrico-querci** [comment]
This is very likely one for the most requested feature. I really hope Amplify will get a native SIWA experience as soon as possible, users will greatly benefit from this

**Comment by philipheinser** [comment]
@thisisabhash this was already requested by a lot of people years ago. https://github.com/aws-amplify/aws-sdk-ios/issues/2633 Im also not sure why this issue before was closed.

**Comment by bdhazman** [comment]
I would love an update on this feature as well.

**Comment by royjit** [comment]
This is not currently supported with Cognito. You can find some detailed explanation about the current situation here: https://github.com/aws-amplify/aws-sdk-ios/issues/2513#issuecomment-774130422 . Closing this issue as duplicate to https://github.com/aws-amplify/aws-sdk-ios/issues/1937

**Comment by philipheinser** [comment]
This issue was a feature request to add support. Dont understand why it gets closed. The other ticket just says you can use the web ui.

**Comment by royjit** [comment]
Apologies for the confusion, both ticket are related because both require us to use a third party authentication like SignInWithApple (which provide native support) and then federate to Cognito User Pool. It is easier for handling the issue and communication at one place. 
As mentioned in the comment https://github.com/aws-amplify/aws-sdk-ios/issues/2513#issuecomment-774130422 you can use native support only with Cognito Identity Pool, we will update the ticket when we have more information regarding similar support in Cognito User Pool.
