### ISSUE TITLE
Identity Pool Facebook federation returns new identityId vs existing Facebook user after 30 to 60 days via AWSMobileClient

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-ios#4073]
**Describe the bug**
AWSMobileClient returns a different identityId for the same Facebook federated users.  

(note, unauthenticated access is disabled and AWSMobileClient returns a different identityId for the same authenticated user)

Using AWSMobileClient with a Facebook federated identity returns a unique identityId ( via `WSMobileClient.default().getIdentityId()` ) upon successful initial sign-in and subsequent sign-in.  This `identityId` is used to uniquely identify a user. After a period of 30 to 60 days, roughly, a future call, most likely due to an expired facebook access token, after a re-authentication using the AWSMobileClient Drop-in UI,  returns a different `identityId`. Thus, users have a new account (and records stored with the identityId do not correlate to this same user).

**To Reproduce**
1. AWSMobileClient using DropIn UI, user signs into Facebook
2. identityId stored in database as unique ID for federated user
3. wait 30 to 60 days
4. Same user attempts to sign-in, user presented `AWSMobileClient.default().showSignIn(...)`
5. After successful facebook authentication via the Drop-in UI, `AWSMobileClient.default().getIdentityId()` returns a different user ID. (note that guest IDs are not a factor here and are not being used).

**Observed Behavior**
`AWSMobileClient.default().getIdentityId()`  returns different a different identityId for some users when using Facebook federated sign-in.

**Expected Behavior**
Federated Facebook users should retain the same identityId, even when access tokens expire, etc. 

**Environment(please complete the following information):**
 - SDK Version: 2.27.1 
 - Dependency Manager: pods
 - Swift Version : 5
 - Xcode Version: 13.3

**Device Information (please complete the following information):**
 - Device: any iOS
 - iOS Version: 15.x.x
 - Specific to simulators: No

**Additional context**
I have one real-world user that has experienced this issue twice. He often does not use the my AWSMobileClient app for 30 to 60 days, but continues to use Facebook frequently. When he signs into my app using Facebook via Drop-in UI, his data is missing since he received a different identityId.

**Comment by atierian** [comment]
Thanks for opening this issue @BillBunting.
We'll take a look at it and post updates here.

**Comment by ameter** [comment]
Hi @BillBunting, we have been attempting to reproduce this issue without success.  The access tokens returned from the FaceBook iOS SDK expire in ~60days and are extended when used within some proximity of expiration.  Assuming this is an issue with re-authenticating a user after the Facebook access token has expired, this would explain why this is only occurring for your user that doesn't use the app for longer periods.

The FB iOS SDK doesn't allow configuring the expiration of tokens, so to test this (without waiting 60 days) we hooked the login flow and replaced the token with one that is identical but with a shorter expiration.  Although this doesn't perfectly reproduce the normal expired token flow, it does allow us to trigger re-authentications to the FB SDK due to expired FB access tokens.  Unfortunately, despite trying a number of scenarios (invalidating FB sessions via account settings, letting the token expire while the FB session is valid, etc) we have not been able to cause a new identity to be created.

A couple of questions:
1. Have you been able to reproduce this locally, or have you only observed it with your user in the wild?
2. If you're you able to reproduce it, can you set logging to verbose and capture verbose logs of the re-authenticaton?
3. I'm not sure whether you can correlate the user to the Cognito Identities associated with them, but if you look at in the Identity browser, do any of the identities look incorrect?  For example, does the `Linked logins` column on the right show 1 for every identity, and in the case of FaceBook login, do all of the Linked logins show `graph.facebook.com`?

**Comment by BillBunting** [comment]
@ameter Hello. Thank you very much for your work on this issue. Per your questions:

1. We have not been able to produce this locally. Only in the wild with one specific user where the problem has occurred twice. We have since learned that this user has had and used more than a single Facebook account in the past, but has been using only their newest account for the past few years.
2. Unfortunately,  we do not capture iOS logs to a server/back end. 
3. Yes, when looking at the affected user in the identity browser, the user's account points to a Facebook, but that is all we can see in the identity browser.

I suspect the issue may be related to a user that may have used multiple Facebook accounts from the same iOS device.  Calls to AWSMobileClient.default().getIdentityId() return different ids. We are continuing to monitor and will reopen the issue if we have any more users report this issue. 

Thank you again for your assistance.
