### ISSUE TITLE
There's no AWSCore when adding the package with SPM

### ISSUE THREAD

**Issue by egorbutyrin-mynalabs** [aws-amplify/aws-sdk-ios#4289]
When I try "Add package..." -> search for AWS -> choose aws-sdk-ios there is no AWSCore in library list.
<img width="652" alt="Screenshot 2022-08-31 at 15 08 26" src="https://user-images.githubusercontent.com/101583401/187675308-cbf06f3b-ee79-4525-9721-3c42087c15c1.png">

**Comment by ruisebas** [comment]
Hi @egorbutyrin-mynalabs.

Based on your screenshot, it seems you're adding the [`aws-sdk-swift`](https://github.com/awslabs/aws-sdk-swift) package instead, not `aws-sdk-ios`.

Keep in mind that in order to use `aws-sdk-ios` with SPM, you should use the SPM repo URL: https://github.com/aws-amplify/aws-sdk-ios-spm .

Let us know if you have any more questions.
