### ISSUE TITLE
Build fails when using AWSMobileClient 

### ISSUE THREAD

**Issue by BVIJeet** [aws-amplify/aws-sdk-ios#4458]
When building the project build fails.

AWSMobileClient

<img width="733" alt="Screenshot 2022-12-15 at 10 56 19 AM" src="https://user-images.githubusercontent.com/120622419/207780596-262ae760-9ff8-4460-b3f2-f4902d8f4e4e.png">

**Environment(please complete the following information):**
 - SDK Version: 2.6.35
 - Dependency Manager:  Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version:  iOS 16.2
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ameter** [comment]
This may be caused by an issue with your Podfile, your CocoaPods cache, or your project configuration.  Here's a few troubleshooting steps you can try:

1. Verify your Podfile is correct and ensure that you have the required dependencies under each target that needs them.
2. Delete your CocoaPods cache, Pods folder, and Podfile.lock and reinstall your pods.  You can do that with the following:
```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm Podfile.lock
pod install --repo-update
```
3. Ensure you are opening the workspace file in Xcode `.xcworkspace`, not the project file `.xcodeproj`
