### ISSUE TITLE
AWSChimeSDKMessagingListChannelMembershipsForAppInstanceUserRequest doesn't return a sorted list of channels

### ISSUE THREAD

**Issue by jwarmkessel** [aws-amplify/aws-sdk-ios#4931]
**State your question**
I'm planning on implementing a polling mechanism to listen for updates to any of the channels. However, when I make this request the channels are unordered. Is there another request I should be using or some expected strategy I should be using to retrieve a list of channels with the most recent being channels with the most recent last message timestamp? 

**Which AWS Services are you utilizing?**
Chime

**Provide code snippets (if applicable)**
```
        guard let listChannelMembershipsRequest = AWSChimeSDKMessagingListChannelMembershipsForAppInstanceUserRequest()
        else {
            return
        }
        
        listChannelMembershipsRequest.appInstanceUserArn = appInstanceUserArn
        listChannelMembershipsRequest.chimeBearer = appInstanceUserArn
        listChannelMembershipsRequest.maxResults = 40
        listChannelMembershipsRequest.nextToken = nextToken

        awsChimeSDKMessagingClient?.listChannelMemberships(forAppInstanceUser: listChannelMembershipsRequest) { response, error in
            print(response)
            completion(response, error)
        }
```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 AWSChimeSDKMessaging (2.30.4)
 
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 Cocoapods
 - Swift Version : [e.g. 4.0]
 Swift 5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 Simulator 
 - iOS Version: [e.g. iOS 11.4]
 iOS 16
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ruisebas** [comment]
Hi @jwarmkessel.

According to the [Chime API documentation](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_ListChannelMembershipsForAppInstanceUser.html), it seems there is no option to retrieve the channels sorted.

Since you have a `lastMessageTimestamp` in the `AWSChimeSDKMessagingChannelSummary` available in the response, you could use that to sort your channels on the completion closure.

**Comment by jwarmkessel** [comment]
Yeah, I've done that but the problem is that the messages appear to arrive in the order that they are store on the backend. So let's say there are 1000 messages a new message will be the 1001st. With the way pagination is setup the user would have to scroll multiple times while I manage the sorting of those messages. Seems like a pretty bad experience. Assume I want to render a user experience similar to the iPhone messaging app. Is there a solution for this?

**Comment by ruisebas** [comment]
I'm a bit confused. We were taking about [`ListChannelMembershipsForAppInstanceUser`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_ListChannelMembershipsForAppInstanceUser.html), which returns the list of channels, not messages. [`ListChannelMessages`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_ListChannelMessages.html) returns the list of messages for a channel, and it does support sorting.

Ultimately, the iOS SDK just exposes and invokes the APIs that are published and maintained by the Chime service team. You might want to reach out to them via AWS Support to request changes in their APIs in order to support your use cases.

**Comment by jwarmkessel** [comment]
Apologies, I meant channels.

**Comment by ruisebas** [comment]
I see, thanks for clarifying. As I said in my previous comment, we don't have control on how these APIs behave.

>With the way pagination is setup the user would have to scroll multiple times while I manage the sorting of those messages. Seems like a pretty bad experience

You might already be doing it, but you could try this to mitigate your problem:
- Fetch **all** channels (this includes handling pagination) in the background
- Sort them by `lastMessageTimestamp`.
- Update your UI with the sorted channels.

This way your users won't have to do anything and will only notice the channel list getting updated.

---
Since we have no action on our side, I'm closing this issue.
