### ISSUE TITLE
The deprecated methods of NSKeyedUnarchiver are still being used in AWSCore

### ISSUE THREAD

**Issue by wchenAtfieldwire** [aws-amplify/aws-sdk-ios#5105]
**Describe the bug**
AWSCore as part of the AWSS3 2.33.5 still uses these deprecated methods of NSKeyedUnarchiver including:
1. +[NSKeyedUnarchiver unarchiveObjectWithData:] inside versionSafeUnarchivedObjectOfClass:fromData:error: 
2. + [NSKeyedUnarchiver unarchiveObjectWithData:] inside versionSafeUnarchivedObjectOfClasses:fromData:error:
3. + [NSKeyedUnarchiver unarchiveObjectWithData:] inside versionSafeMutableDictionaryFromData:error:

**To Reproduce**
1. Download AWSS3 version 2.33.5
4. Search the usage of NSKeyedUnarchiver
5. Find the usage of the deprecated methods of NSKeyedUnarchiver

**Observed Behavior**
There are usages of the deprecated methods of NSKeyedUnarchiver inside AWSCore that comes with AWSS3

**Expected Behavior**
No deprecated methods of NSKeyedUnarchiver is being used

**Code Snippet**
One of the examples listed above under "Describe the bug".
```
+ (nullable id)versionSafeUnarchivedObjectOfClasses:(NSSet<Class> *)classes
                                           fromData:(NSData *)data
                                              error:(NSError *__autoreleasing *)error {
    id returnValue;

    if (@available(iOS 11, *)) {
        returnValue = [NSKeyedUnarchiver unarchivedObjectOfClasses:classes
                                                          fromData:data
                                                             error:error];
        if (error && *error) {
            AWSDDLogError(@"Error unarchiving data into allowed classes `%@`: %@", classes, *error);
            return nil;
        }
    } else {
        returnValue = [NSKeyedUnarchiver unarchiveObjectWithData:data];
    }

    return returnValue;
}
```
**Areas of the SDK being used**
AWSCore

**Environment(please complete the following information):**
 - SDK Version: AWSS3 2.33.5
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 15.0

**Comment by 5d** [comment]
Hi @wchenAtfieldwire,

Thank you for raising the issue. Regarding the provided code snippet, the `unarchiveObjectWithData:` method is only being compiled when the iOS version is below 11. This is due to the fact that the successor method, `unarchivedObjectOfClass:fromData:error:`, is only accessible starting from iOS 11. Our library is designed to support a minimum iOS version of 9. We utilize the deprecated method for backward compatibility purposes. If your target platform is iOS 11 or higher, your code will not be compiled with these deprecated methods.

**Comment by wchenAtfieldwire** [comment]
@5d Ah ok thanks for the response. That makes sense!
