### ISSUE TITLE
AWSDDFileLogger doesAppRunInBackground conflict

### ISSUE THREAD

**Issue by mk-wang** [aws-amplify/aws-sdk-ios#5355]
the same issue like https://github.com/aws-amplify/aws-sdk-ios/issues/643

duplicate symbol '_doesAppRunInBackground' in:
   .../Build/Products/Debug-iphonesimulator/CocoaLumberjack/CocoaLumberjack.framework/CocoaLumberjack[11](DDFileLogger.o)
   .../Build/Products/Debug-iphonesimulator/AWSCore/AWSCore.framework/AWSCore[22](AWSDDFileLogger.o)
ld: 1 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 5d** [comment]
Thank you for submitting the issue. Could you specify which version and packages you are using?

**Comment by mk-wang** [comment]
AWSCore : 2.36.2

AWSCore/Logging/AWSDDFileLogger.m

it’s related to https://github.com/aws-amplify/aws-sdk-ios/pull/5222, which use the same function name (doesAppRunInBackground) of CocoaLumberjack. And doesAppRunInBackground symbol is extern exported.
Pls change it to static function 

![IMG_5232](https://github.com/aws-amplify/aws-sdk-ios/assets/700254/03f8de03-858c-4896-ae76-8c7f068aea2f)

Just Make doesAppRunInBackground

**Comment by mzying2013** [comment]
我遇到了同样的问题，是关于CocoaLumberjack和AWSIoT之间的冲突。CocoaLumberjack的版本是3.8.5，而AWSIoT的版本是2.36.2。为了解决这个问题，我不得不将AWSIoT降级到2.35.0版本。 老实说，AWSIoT难道不能简单地依赖CocoaLumberjack吗？为何非要将CocoaLumberjack复制进AWSIoT，并为所有类名添加AWS前缀？这种做法难道不让你们感到尴尬吗？

I encountered the same issue due to a conflict between CocoaLumberjack and AWSIoT. CocoaLumberjack is at version 3.8.5, while AWSIoT is at 2.36.2. To resolve this issue, I had to downgrade AWSIoT to version 2.35.0. Honestly, can't AWSIoT simply depend on CocoaLumberjack? Why must they copy CocoaLumberjack into AWSIoT and prepend all class names with 'AWS'? Doesn't this approach make you feel embarrassed?
