### ISSUE TITLE
AWSMobileClientXCF not available as cocoapods package

### ISSUE THREAD

**Issue by dbrkic-proglove** [aws-amplify/aws-sdk-ios#5409]
**Describe the bug**
Currently, there is a .podspec file available for the AWSMobileClient package, but not for the AWSMobileClientXCF package. Since I am using AWSMobileClientXCF in my own package with SPM, I am not able to distribute my package with cocoapods because I can't list AWSMobileClientXCF in our dependencies. Is there a workaround for this?

**To Reproduce**
1. Create an Xcode project with a framework target that uses  AWSMobileClientXCF as dependency via SPM
2. Build out an .xcframework
3. Create a cocoapods .podspec with this .xcframework added locally

**Observed Behavior**
Because my package uses AWSMobileClientXCF as dependency, and a podspec for AWSMobileClientXCF doesn't exist, I have to add it by manually downloading AWSMobileClientXCF.xcframework and placing it in the vendored_frameworks

**Expected Behavior**
I should be able to list AWSMobileClientXCF as dependency by adding the following line: `s.dependency 'AWSMobileClientXCF'`

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Environment(please complete the following information):**
 - SDK Version: 2.36.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5.10
 - Xcode Version: 15.0

**Comment by ruisebas** [comment]
Hi @dbrkic-proglove, thanks for opening this.

The reason why the `AWSMobileClientXCF` module exists when consuming the SDK through XCFrameworks (such as with SPM) is because [you cannot have a type with the same name as the module](https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962/2). When consumed through CocoaPods, the module is just called `AWSMobileClient`.

You have a quite unique use case, as you're consuming the module through the SPM's XCFrameworks, including it in another XCFramework and then distributing that one through CocoaPods.

I will explore if there are any other workarounds/alternative besides including the `AWSMobileClientXCF.xcframework` file yourself and post any updates here

**Comment by dbrkic-proglove** [comment]
@ruisebas thank you very much for the swift response :)

**Comment by ruisebas** [comment]
Hi @dbrkic-proglove. 
Unfortunately it seems the only feasible solution for your use case is to download the `AWSMobileClientXCF.xcframework` and vend it yourself, as you are already doing.

We currently don't have plans to distribute XCFrameworks through CocoaPods.
