### ISSUE TITLE
Unable to set Identity Provider Manager multiple times

### ISSUE THREAD

**Issue by AutumnMageKate** [aws-amplify/aws-sdk-ios#588]
Our application uses a core object `Authenticator` to handle all of the AWS/Facebook/etc authentication of the application. This `Authenticator` object, on initialization, initializes a number of objects needed to do all of the authentication; among these objects is an instance of `AWSCognitoCredentialsProvider`, which is not a singleton and is not static. It is an instance variable of our instance of the `Authenticator`.

We want to have a suite of tests to demonstrate that we handle a variety of cases around the `Authenticator` correctly, such as "user puts in correct username/password" and "user logs out then logs back in". What we are finding, however, is that the _exact same test_ will pass the first time and fail the second time.

This simple test is to test basic Cognito User Pools login, and run individually, each works; but when run as part of the same test run, then whichever one is run second fails.

It appears that what is happening is that in the first test, when `cognitoCredentialsProvider.credentials` is called, it properly calls our class conforming to `AWSIdentityProviderManager` to get the tokens. In the second test, however, it does not call this class.

We have narrowed it down to `-[AWSCognitoCredentialsProvider setIdentityProviderManagerOnce:]`. It appears that when instance 1 of the `AWSCognitoCredentialsProvider` has this called, it properly sets the identity provider manager. However, when instance 2 (remember, there are absolutely no indications of being expected to be a singleton or static in any way, in either code or documentation—that I have seen, at least) of the `AWSCognitoCredentialsProvider` has this called, then nothing happens. It fails to set the identity provider manager.

This is baffling behavior. While I can appreciate that on a given `AWSCognitoCredentialsProvider` instance I can only set the Identity Provider Manager once (though I still don't actually understand why that is, and the method has no documentation comment to explain itself), I cannot for the life of me understand why I cannot set it again on a different instance of the class.

How can I properly test my various initialization/authentication flows against Cognito if I can't actually initialize the objects more than once?

**Comment by kdbertel** [comment]
Any idea if this has been addressed in the latest versions of the SDK?

**Comment by kdbertel** [comment]
It does not make it "super clear". It indicates that for a particular instance of the object, I can only do the thing once. I would _never_ expect that an _instance_ method on a class could only be called once for _all instances of that class_. It's not a standard API paradigm, and wasted hours of my time trying to figure out what was going on, instead of being productive and writing tests and code.

It's not an issue of the number of credential providers. It's an issue of _properly testing my code_. One of the core ideas of writing tests is that they are Independent, meaning running one test should not have a side effect that affects the running of any other tests. This pseudo-static-but-pretending-not API breaks that capability.

Though, it's also been over a year since I raised this issue; we solved it by making our tests less good for a while, and then by dropping AWS authentication altogether in favor of one that had a sane API, up-to-date documentation, and a responsive dev team.

It would appear that this issue is still around in the AWS SDK, however.

**Comment by kdbertel** [comment]
If something only happens once in the lifetime of the app, it should be marked as static/class.

The code in question was part of a library being used by a much larger app. There was no app delegate. And if I didn't test where the SDK interacted with the code, then I'd literally have no tests, and no way of automatically knowing whether or not a test user can properly log in against our backend.

I think it is distinctly problematic if a library produced by a tech giant actively incentivizes people to write software poorly in order to make it work with the library. Libraries should support good coding practices.
