### ISSUE TITLE
AWS AuthUI without Navigation Controller

### ISSUE THREAD

**Issue by pershanti** [aws-amplify/aws-sdk-ios#815]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS AuthCore, AWS AuthUI

* In what version of SDK are you facing the problem?
2.6.6

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

The current way to present an AWSAuthUIViewController is:
AWSAuthUIViewController.presentViewController(with: UINavigationController, configuration: AWSAuthUIConfiguration?, completionHandler: AWSAuthUICompletionHandler), 

which requires you to be using a Navigation Controller. However, I don't want to embed my login screen in a navigation controller. Is there a way for me to present the AuthUIViewController without?

**Comment by rohandubal** [comment]
Hello, currently there is no other way to use the AuthUI. It requires using navigation controller. 

I will take this as a feature request to the team. Could you elaborate a little more on your use case to help us understand the feature better?

Thanks,
Rohan

**Comment by masarusanjp** [comment]
I have same issue.
So I avoid this issue by following code .

```
let viewController = UIViewController()
let navigationController = UINavigationController(rootViewController: viewController)
// To present empty UINavigationController as modal without animation.
UIApplication.shared.delegate?.window?.rootViewController?.present(navigationController, animated: false, completion: nil)
if !AWSSignInManager.sharedInstance().isLoggedIn {
    AWSAuthUIViewController
        .presentViewController(with: navigationController,
                               configuration: nil,
                               completionHandler: { (provider: AWSSignInProvider, error: Error?) in
                                navigationController.dismiss(animated: false, completion: nil)
                                if error != nil {
                                    print("Error occurred: \(String(describing: error))")
                                } else {
                                    // Sign in successful.
                                }
        })
}
```

Looking at the current implementation, it seems unnecessary to depend on UINavigationController.
 
https://github.com/aws/aws-sdk-ios/blob/master/AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIViewController.m#L43

I hope this dependency is gone in the next version

**Comment by mathieugarcia** [comment]
Hello!

I second this request. My app uses a custom widget library and rely only occasionally on UIKit widgets. Most 3rd party SDK we use, that have custom UI's, use `UIViewController`'s, not `UINavigationController`'s.

Thanks for considering this!

Cheers,
Mathieu.

**Comment by RushanB** [comment]
I am having a problem with the keyboard in AWSAuthUIViewController. When clicking on username textfield or password textfield it moves both of upwards and out of the view. How can I fix this? I just started experiencing this when I updated to Swift 4.1.

**Comment by King-Kira** [comment]
@RushanB I have the same issue. I tested it on different versions of iPhone in the XCode simulator and the issue doesn't happen for iPhone X. 
It used to be that the view wouldn't move upward but that the keyboard would (at least partially) block the textfields. This problem appeared recently and I'm unsure as to what can be done about it.

**Comment by RushanB** [comment]
@King-Kira Yes, I remember but that was at least usable. At the moment a user can't even Sign In as they can't see what they are typing.

**Comment by King-Kira** [comment]
I know. It's quite frustrating.
I posted a new issue on this Git if you want to comment on it.
https://github.com/aws/aws-sdk-ios/issues/878

**Comment by rohandubal** [comment]
The issue regarding the keyboard is resolved in the latest release `2.6.17`

Thanks,
Rohan

**Comment by 24601** [comment]
@rohandubal - a use case is any application that uses XCode's Document-based template/patterns, these view controller hierarchies have null NavigationControllers because they are Document based.

We have this issue.

**Comment by EthanLozano** [comment]
@masarusanjp solution worked for me with the slight annoyance that AWSAuthUIViewController [presents itself with an animation](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSAuthUI/AWSAuthUIViewController.m#L44) and [dismisses itself with an animation](https://github.com/aws/aws-sdk-ios/blob/2.6.23/AWSAuthSDK/Sources/AWSUserPoolsSignIn/AWSUserPoolsUIOperations.m#L100). So, there is a brief black background when the login view is presenting and dismissing. It would be nice if these animation values were configurable. I also had to call that code in `viewDidAppear` (rather than `viewDidLoad`) within my main view controller to avoid getting this: `Warning: Attempt to present [UINavigationController] on [] whose view is not in the window hierarchy!`

Unless I'm mistaken, the login view relies on having a navigation controller, so it's more a question about who supplies the navigation controller. As written, `AWSAuthUIViewController.presentViewController` seems to assume the user has a UINavigationController UI. But, the user could also want the login view to be presented within a modal, and it would be nice if the API supported this out of the box. Perhaps the API could have an overloaded `presentViewController` method that presents the login view within a modal?

**Comment by thomers** [comment]
I second this request - if you look at the code in AWSAuthUIViewController, it creates its own UINavigationController and uses the passed navigation controller only to call presentViewController (which is a UIViewController method, anyway!).

**Comment by atierian** [comment]
Thanks for this feature request. We recommend using [Amplify Authenticator](https://ui.docs.amplify.aws/swift/connected-components/authenticator), which has extensive customization options.
